### ISSUE TITLE
Inexistent multi-language feature in version 1.0.2 (latest available release at the time of this post)

### ISSUE THREAD

**Issue by luissalgadofreire** [MicrosoftDocs/composer-docs#1]
I have installed Bot Framework Composer version 1.0.2 as an installable desktop application in Mac and the multi-language options shown in this documentation page - namely the dropdown in settings to add languages - is inexistent. Can you clarify if this feature does in fact already exist and from which release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e3f9d9-a593-40a3-bd68-1235966cca23
* Version Independent ID: 6984f534-80f3-6bd8-0392-b1cedf86393a
* Content: [Multiple language support - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language)
* Content Source: [composer-docs/how-to-use-multiple-language.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-use-multiple-language.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
The multilingual feature does not exist for the 1.0.2 version yet. It's in the upcoming release of Composer, we are getting very close to release the product soon. For some reason from the publishing team, our updated docs were merged to live on August 24, 2020. Please wait for a few days to try the multilingual feature.

**Comment by zxyanliu** [comment]
FYI.  [Composer 1.1.0](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.1.0) was released today, you can try the multilingual feature now! 
Thanks.

**Comment by luissalgadofreire** [comment]
Thanks, @zxyanliu. Just installed it and can confirm multilingual is now available.

**Comment by zxyanliu** [comment]
@luissalgadofreire great! Thanks!
