### ISSUE TITLE
Why is an Azure Search service created as part of the deployment script

### ISSUE THREAD

**Issue by knightmeister** [MicrosoftDocs/composer-docs#10]
The deployment script for App Service deployment (untested with Azure Functions) creates a standard-tier Azure Search Service. This is an expensive resource. Can we please get it documented why this is created and what it is used for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @knightmeister this is not an issue about docs. 
If you have feedback on the product itself, you can report the issue on this repo: https://github.com/microsoft/BotFramework-Composer

**Comment by zxyanliu** [comment]
Closing since this issue is not related to docs.
