### ISSUE TITLE
Typo error in the tutorial-get-weather documentation

### ISSUE THREAD

**Issue by rakesh-vardan** [MicrosoftDocs/composer-docs#101]
[Please fix the typo in the below line in first paragraph:

`The but will prompt the user for their zip code, then responds with the weather forecast for the specified location based on a query to an external service.` 

It should be `The bot will prompt the user for their zip code, then responds with the weather forecast for the specified location based on a query to an external service.`]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc39a432-6924-dbfd-42b8-bab7df273e77
* Version Independent ID: acfd500f-7115-aea9-a99b-c67764f61119
* Content: [Tutorial: Add actions to a bot - Bot Composer](https://docs.microsoft.com/en-in/composer/tutorial/tutorial-get-weather)
* Content Source: [composer-docs/tutorial/tutorial-get-weather.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-get-weather.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Thanks for reporting. Working in progress. The content will be updated and go live soon.

**Comment by zxyanliu** [comment]
The fixing PR was merged and the content will go live soon.
Thanks again for your report. Closing the issue now as it is addressed.
