### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by aman5898** [MicrosoftDocs/composer-docs#103]
[Enter feedback here]

In the first line, it should be bot

![image](https://user-images.githubusercontent.com/32238811/109554724-99761f00-7afa-11eb-957a-48b52f69a18e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc39a432-6924-dbfd-42b8-bab7df273e77
* Version Independent ID: acfd500f-7115-aea9-a99b-c67764f61119
* Content: [Tutorial: Add actions to a bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-get-weather)
* Content Source: [composer-docs/tutorial/tutorial-get-weather.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-get-weather.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
FYI. This issue has been fixed in the master branch and the content will go live soon.
Thanks for your feedback.
