### ISSUE TITLE
Upgrade to WebSocket is required Error

### ISSUE THREAD

**Issue by mmarzillo** [MicrosoftDocs/composer-docs#104]
I have the appropriate App Id and Password configured as well as turning on Websockets in the portal but I'm still getting the "Upgrade to WebSocket is required" error when I attempt to run my consumer bot in the emulator. Hoping I'm missing something simple.

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a631930-1f27-93a4-7d70-79cdc6ee3bb3
* Version Independent ID: 8506ad08-a04a-31d6-46a0-24c4654c8705
* Content: [Connect to skills - Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill#create-azure-registration-resources)
* Content Source: [composer-docs/how-to-connect-to-a-skill.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-connect-to-a-skill.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Closing this issue as it has been addressed.
