### ISSUE TITLE
Development Pipelines for Composer

### ISSUE THREAD

**Issue by mmarzillo** [MicrosoftDocs/composer-docs#106]
Is there any plan to integrate Composer with Git or Azure Devops for easier development pipelines? Or is there a streamline process available now that I'm missing?

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Closing this issue for now since it has been resolved and the updated content will go live soon.
