### ISSUE TITLE
Bot Framework Composer multi choice with Hero Card

### ISSUE THREAD

**Issue by IAmDharam** [MicrosoftDocs/composer-docs#108]
I have a Multi choice input where I have 8 options as Hero card. I Have also written 8 triggers of type Regular expression recognizer for the same 8 options in multi choice input. When I select any input from the options for the first time, the trigger does not Invoke but when I select again for the second time, the trigger works. Can anyone help me with this? I am new to Bot Framework Composer.

**Comment by WashingtonKayaker** [comment]
@IAmDharam An approach for this is demonstrated in the **_Responding With Cards Sample_**

![image](https://user-images.githubusercontent.com/52054121/113353346-5cb46800-92f2-11eb-825f-3975645385c2.png)

**Comment by WashingtonKayaker** [comment]
Closing - no response. @IAmDharam if you are still having problems or have identified an error in the documentation, please feel free to open a new issue.
