### ISSUE TITLE
If statement samples don't use the correct syntax

### ISSUE THREAD

**Issue by iMicknl** [MicrosoftDocs/composer-docs#109]
Currently the samples are broken on this page, correct statements require another dash (-) in fron of the IF/ELSE. See [.lg file format reference](https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0#conditional-response-template).

```
- IF: ${timeOfDay == 'morning'}
    - good morning
- ELSE:
    - good evening
```

I am not able to find the documentation in this repo, thus not able to propose the change myself..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8fd4a76-f071-477d-57b4-fd746c1c682e
* Version Independent ID: 3947e8f1-28bc-d8e3-daeb-b8522317700b
* Content: [Language generation in Bot Framework Composer - Bot Composer](https://docs.microsoft.com/en-us/composer/concept-language-generation)
* Content Source: [composer-docs/concept-language-generation.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/concept-language-generation.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
@iMicknl Thanks for reporting the issue. That's a nice catch! Fixing the syntax.

**Comment by WashingtonKayaker** [comment]
@iMicknl Thank you for reporting this issue, it has been addressed and the updates have been checked in.
