### ISSUE TITLE
Documented steps for Azure function errors out

### ISSUE THREAD

**Issue by saikumaru** [MicrosoftDocs/composer-docs#11]
I have followed the steps for publishing bot to Azure Function with resources created through the commandline script

[Enter feedback here]
The Function App shows up the below error
![image](https://user-images.githubusercontent.com/44021002/94023738-30b0ab00-fdd4-11ea-9d73-1818910fa154.png)

And the status of the runtime shows as error
![image](https://user-images.githubusercontent.com/44021002/94023816-48882f00-fdd4-11ea-99e5-ac82a7caf89c.png)

And the diagnosis says
![image](https://user-images.githubusercontent.com/44021002/94023986-7bcabe00-fdd4-11ea-9e47-2963951bc164.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
This is related to: https://github.com/microsoft/BotFramework-Composer/issues/4243
We will look into this issue and get back go you.
Thanks!

**Comment by saikumaru** [comment]
Sure please. I had opened two as i dint know which one would be relevant, whether docs are wrong or the script of publish.

Appreciate your input if you can guide atleast with a work around in the interim

Thanks

**Comment by zxyanliu** [comment]
No worries. It should be related to the product side. 
We can keep this one open for possible updates to the docs. 
Thanks!

**Comment by zxyanliu** [comment]
Closing the issue because of this: https://github.com/microsoft/BotFramework-Composer/issues/4243

**Comment by zxyanliu** [comment]
Let's keep this tracking via https://github.com/microsoft/BotFramework-Composer/issues/4243
