### ISSUE TITLE
Knowledge base doesn't get published according to these instructions

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/composer-docs#110]
This document says the way to publish a knowledge base from Composer is just to start the bot, but that information is incomplete. The knowledge base only gets published if you're using a QnA intent trigger with the default recognizer. If you're only accessing QnA Maker through a QnA Maker dialog, the knowledge base won't get published.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b758ea7f-6c95-34d2-4af8-27e182d25093
* Version Independent ID: 369b9a72-f015-17cc-ca77-c7f9c27deae0
* Content: [Create a QnA Maker knowledge base in Composer - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb)
* Content Source: [composer-docs/how-to-create-qna-kb.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-create-qna-kb.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
@v-kydela can you please look at the docs again and if this is still an issue, let me know? We recently released updates to the docs for the 1.4 release which may have addressed this issue.

**Comment by v-kydela** [comment]
@WashingtonKayaker - I see no change to the publishing section of the doc, and I just confirmed that Composer still does not publish the knowledge base unless the default recognizer is used

**Comment by WashingtonKayaker** [comment]
@v-kydela Thanks Kyle, I'm looking at this currently and am not sure what you mean:

> If you're only accessing QnA Maker through a QnA Maker dialog, the knowledge base won't get published.

What is a "a QnA Maker dialog"?

**Comment by v-kydela** [comment]
![image](https://user-images.githubusercontent.com/41968495/113741129-31e15f80-96b6-11eb-9a9d-a4a12d1b270e.png)

![image](https://user-images.githubusercontent.com/41968495/113741043-1d9d6280-96b6-11eb-9000-7402a83150bf.png)

**Comment by WashingtonKayaker** [comment]
@v-kydela I made some updates that I hope will address this issue, if not let me know.

**Comment by v-kydela** [comment]
@WashingtonKayaker - Do your changes say anything about QnAMaker dialogs versus QnA Maker intent triggers?

**Comment by JonathanFingold** [comment]
@mmiele Please follow up with Dana VanHooser as to whether this is adequately addressed.

**Comment by dmvtech** [comment]
There are two routes for using QnA in Composer.

One is to use an action (not a _dialog_) to make an specific/explicit call to QnA with an action. This is described in the [Add QnA to your bot](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot?tabs=v2x) article. This route does not allow any authoring or two-way connectivity (again; just a way to query QnA from an action). There is no publishing available with this route.

The other is to author QnA from Composer and utilize the QnA triggers/recognizers/dialogs. This allows and **requires** authoring from Composer, as well as recognition of QnA intents and dialog triggers. This is described in the article [Create a QnA Maker knowledge base.](https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb?tabs=v2x) With this, publishing is required and does happen.

**Comment by mmiele** [comment]
Solved.
