### ISSUE TITLE
Publish bot framework composer to app service

### ISSUE THREAD

**Issue by rajasweet14** [MicrosoftDocs/composer-docs#112]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot#publish)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

Hi frist thanks for creating a wonderful application like bot framework composer 

In general lot need to improve in document or else set up a bot which cover each and every concept like a real chat bot demo video or tutorial in lot deep concept,
 I am here because I tried to publish a test bot to azure app service but I am failed many times ,I am tried to publish in existence resource group of azure using publish settings in bot framework composer

I am getting error like 400 status code and the json object at o is not valid

1.How I get access token ? Az login is not worked out for me ,give someother option
2. whether I need to give complete host name ?like https or else just name 
3. Is there is any detail document of publish app please send me that 

I build a bot it is in local I tried to publish app service this issue happened .... I followed complete bot composer document to build bot ...thanks for all all open source bot framework composer! Pls improve document by step step ..lot of things are missing without detail explanation
 logs:
---
"Accepted for publishing..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"start publish luis"
---

---
"Assigning to luis app id:<my app id is showen its correct one>
---

---
"{\"name\":\"StatusCodeError\",\"statusCode\":400,\"message\":\"400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\",\"error\":{\"error\":{\"message\":\"Failed to parse azure account information object object.\"}},\"options\":{},\"response\":{\"statusCode\":400},\"stack\":\"StatusCodeError: 400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\\n    at new i (C:\\\\Users\\\\rajamanikkam.b\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:110597)\\n    at F.callback (C:\\\\Users\\\\rajamanikkam.b\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:109440)\\n    at F.e.callback.t.callback [as _callback] (C:\\\\Users\\\\rajamanikkam.b\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:108488)\\n    at F.t._callback.t.callback.t.callback (C:\\\\Users\\\\rajamanikkam.b\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:4017)\\n    at F.emit (events.js:210:5)\\n    at F.<anonymous> (C:\\\\Users\\\\rajamanikkam.b\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:16714)\\n    at F.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (C:\\\\Users\\\\rajamanikkam.b\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:15546)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"
---

---
"{\"stack\":\"SyntaxError: Unexpected token o in JSON at position 1\\n    at JSON.parse (<anonymous>)\\n    at Object.<anonymous> (C:\\\\Users\\\\rajamanikkam.b\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:115579)\\n    at C:\\\\Users\\\\rajamanikkam.b\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:112703\\n    at Object.throw (C:\\\\Users\\\\rajamanikkam.b\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:112808)\\n    at s (C:\\\\Users\\\\rajamanikkam.b\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:111573)\",\"message\":\"Unexpected token o in JSON at position 1\"}"
---

---
"SyntaxError - Unexpected token o in JSON at position 1"
---
publish settings :
{
  "name": "<given my app name>",
  "environment": "dev",
  "runtimeIdentifier": "win-x64",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": ""
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "",
      "authKey": "",
      "databaseId": "botstate-db",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "",
      "container": ""
    },
    "luis": {
      "authoringKey": "<given my luis authoringKey>",
      "authoringEndpoint": "<given my authoringEndpoint>",
      "endpointKey": "",
      "endpoint": "",
      "region": "westus"
    },
    "MicrosoftAppId": "<my app id>",
    "MicrosoftAppPassword": "<my app password>"
  },
  "accessToken": "<login graph and clicked accessToken on graph explore append here thoes accessToken",
  "hostname": "<my host name>"
}

With love with bot framework composer
Raja manikkam.b

**Comment by WashingtonKayaker** [comment]
@rajasweet14 Thank you for your questions and comments.  I did not write this article, and saw it for the first time as a result of my looking into this issue. I stepped through the instructions and everything worked, so I am not sure what went wrong on your end. If you can provide detailed steps to reproduce this issue I might be able to help. I would also suggest posting support related questions on [stackoverflow.com](https://stackoverflow.com/) (tag your questions with [botframework] ), and if you have comments about specific errors in the docs, please post them here and we will be happy to make the required updates.

**Comment by WashingtonKayaker** [comment]
Closing - no response. @rajasweet14 if you are still having problems or have identified an error in the documentation, please feel free to open a new issue.
