### ISSUE TITLE
on 12th step when we should to start Bot there is the error 

### ISSUE THREAD

**Issue by nastya2090** [MicrosoftDocs/composer-docs#113]
Error:
Luis build failed: The apps - Get applications list Operation under LUIS Programmatic APIs v3.0-preview is not supported with the current subscription key and pricing tier LUIS.F0.

What can I do to fix it?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c55e6920-2987-2b78-66b7-3dee92ab8689
* Version Independent ID: 5d9f5e75-ee25-cc5d-bdd5-594712badf63
* Content: [Tutorial: Add language understanding to bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis)
* Content Source: [composer-docs/tutorial/tutorial-luis.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-luis.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
@nastya2090: This error is a LUIS error. Once you have completed step #12 you need to setup and configure LUIS before running your bot, as described in the following section titled [Create LUIS resource](https://docs.microsoft.com/composer/tutorial/tutorial-luis#create-luis-resource). Make sure that you create a authoring resource and provide the correct authoring key in your project settings.

![image](https://user-images.githubusercontent.com/52054121/113339151-e9edc180-92de-11eb-84d9-172460e11ddc.png)

If you have already done this, and are still having problems, please let me know.

**Comment by WashingtonKayaker** [comment]
Closing - no response.
