### ISSUE TITLE
the link for http request doesn't work 

### ISSUE THREAD

**Issue by nastya2090** [MicrosoftDocs/composer-docs#115]
Hi! I checked this link, i pasted zip code and API token.
http://weatherbot-ignite-2019.azurewebsites.net/api/getWeather?zipcode=${user.zipcode}&api_token=Your_API_Token

I see the message Can't find the server IP address for weatherbot-ignite-2019.azurewebsites.net.

Please, fix it )

**Comment by zxyanliu** [comment]
Hi, did you have a chance to get an API token from the [OpenWeather website](https://openweathermap.org/)

In the doc: 
![image](https://user-images.githubusercontent.com/32497439/112530674-f6649e00-8d63-11eb-8526-15bcee5cc9bf.png)

**Comment by zxyanliu** [comment]
Please refer to the comment and example URL in the following issue: 
https://github.com/MicrosoftDocs/composer-docs/issues/117
