### ISSUE TITLE
Url from the example is not working

### ISSUE THREAD

**Issue by jagojar** [MicrosoftDocs/composer-docs#116]
In the example, this is the link used:

http://weatherbot-ignite-2019.azurewebsites.net/api/getWeather?zipcode=${user.zipcode}&api_token=Api_Key

that link is not working. I suspect the cause is that it was used for an event (Ignite, I guess).

Could you update the link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc39a432-6924-dbfd-42b8-bab7df273e77
* Version Independent ID: acfd500f-7115-aea9-a99b-c67764f61119
* Content: [Tutorial: Add actions to a bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-get-weather)
* Content Source: [composer-docs/tutorial/tutorial-get-weather.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-get-weather.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Duplicate. Please read comment and an example URL provided in the following issue: https://github.com/MicrosoftDocs/composer-docs/issues/117
