### ISSUE TITLE
The URL referred http://weatherbot-ignite-2019.azurewebsites.net ... does not work anymore

### ISSUE THREAD

**Issue by orcelik** [MicrosoftDocs/composer-docs#117]
The URL referred http://weatherbot-ignite-2019.azurewebsites.net/api/getWeather?zipcode=${user.zipcode}&api_token=Your_API_Token does not work anymore, because  http://weatherbot-ignite-2019.azurewebsites.net is not available anymore. 
I made it work with following URL, I suggest to change accordingly
http://api.openweathermap.org/data/2.5/weather?zip=${user.zipcode},us&appid=Your_API_Token

Rationale: In the page its requested to get an API key from openweathermap.org, so the weatherbot-ignite-2019.azurewebsites.net was redirecting to that site. If we look at the API documentation in the following link, it shows the above  suggested format is correct (Also I verified that above format works) https://openweathermap.org/current#zip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc39a432-6924-dbfd-42b8-bab7df273e77
* Version Independent ID: acfd500f-7115-aea9-a99b-c67764f61119
* Content: [Tutorial: Add actions to a bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-get-weather)
* Content Source: [composer-docs/tutorial/tutorial-get-weather.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-get-weather.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by networkengineerdelta** [comment]
Same issue here. I would also add a note on how to select the units.

https://api.openweathermap.org/data/2.5/weather?zip=${user.zipcode},us&units=imperial&appid=Your_API_Token

**Comment by zxyanliu** [comment]
Thanks for reporting the issue. I will take a look and get back to you soon.

**Comment by zxyanliu** [comment]
@orcelik and @networkengineerdelta 
Thanks again for your feedback. I just tested and verified that the URL provide by @networkengineerdelta worked perfectly on my end.

**Comment by zxyanliu** [comment]
FYI. We have already updated the URL in [this PR](https://github.com/MicrosoftDocs/composer-docs-pr/pull/391). 
The content will be merged and published to live soon. 
Thanks again for your feedback.

**Comment by zxyanliu** [comment]
Closing as the issue has been fixed and the content is live. 
Thanks for your feedback.
