### ISSUE TITLE
Please add LUIS Bot Multilingual Sample

### ISSUE THREAD

**Issue by anniexudan** [MicrosoftDocs/composer-docs#118]
On this page of the document. Could you add more details about how to make Bot with LUIS to support multi-language? I am seeing an error when trying to Start the Bot saying that missing {Botname}.es file.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e3f9d9-a593-40a3-bd68-1235966cca23
* Version Independent ID: 6984f534-80f3-6bd8-0392-b1cedf86393a
* Content: [Multiple language support - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language)
* Content Source: [composer-docs/how-to-use-multiple-language.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-use-multiple-language.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @anniexudan thanks for reporting the issue.
Can you please share more details about your error message? If you follow the instructions covered in this [doc](https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language), you should be able to make it work. :-)

FYI. We are releasing our docs for Composer 1.4 release. There will be a lot of updates coming.

**Comment by anniexudan** [comment]
Hi @zxyanliu , thanks for reaching out. I was following the doc you mentioned. Works fine. However, the challenge and issue is that when the Bot has LUIS intents it does not work. It would be nice to have a Blog about how to build a Multi-Lingual Bot in Composer with LUIS or QNA.
![image](https://user-images.githubusercontent.com/48502175/112682663-ce9a3680-8e46-11eb-935e-e2baf555ee9f.png)

**Comment by anniexudan** [comment]
hi @zxyanliu , I found where the issue is. I tested in 'zh-cn' with LUIS intent Bot and it works fine. However, when it is 'zh', it does not work. Maybe in the documentation, we can add what languages are supported?

**Comment by zxyanliu** [comment]
Yes, that's a nice catch. This is [the updated content in the PR](https://github.com/MicrosoftDocs/composer-docs-pr/blob/1.4/composer-docs/how-to-use-multiple-language.md).

The content should go live soon.

**Comment by zxyanliu** [comment]
Feel free to reach out to me on Teams via:
Yan.Liu@teksystemsgs.com

**Comment by zxyanliu** [comment]
The content has been updated to specify the default language locale. 
https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language#test

Let me know if you still have questions/confusion.

Thanks a lot!

**Comment by zxyanliu** [comment]
Closing this issue for how as the content has been updated and published to live.
