### ISSUE TITLE
Various typos found in docs

### ISSUE THREAD

**Issue by plwhite** [MicrosoftDocs/composer-docs#119]
Various typos:

- `Wheatherbot` instead of `weatherbot` in at least one place (on the "Add help and cancel command" page)
- Section 9 of "Create a bot" page has `it's` in a place where it should be `its`
- In the Overview, "Introduction to the Bot Framework Composer" page the link to "Language Generation" is broken. It's to <https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-adaptive-dialog-Introduction-generators>, when I think you probably mean <https://docs.microsoft.com/en-us/composer/concept-language-generation>.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e6663c-4d8c-5c93-ae66-8b556af3ad4d
* Version Independent ID: 5acb7423-f108-1bea-8888-ef620308e3f0
* Content: [Tutorial: Add help functionality to a bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-add-help)
* Content Source: [composer-docs/tutorial/tutorial-add-help.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-add-help.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
@plwhite Thank you for reporting these issues, all have been addressed and will be in the docs soon.
