### ISSUE TITLE
OAuth prompt should store in turn.token, not dialog.token

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/composer-docs#121]
Page needs to be updated to reflect the best practices storage location for user tokens

**Comment by JonathanFingold** [comment]
@clearab - Please indicate which topic you noticed this issue in.

**Comment by clearab** [comment]
Hrm, this doesn't track against the page I was on when I opened the issue anymore? It was this article: https://docs.microsoft.com/en-us/composer/how-to-use-oauth#configure-the-oauth-connection-settings-in-composer

**Comment by JonathanFingold** [comment]
Fixed in Composer and in master.

**Comment by JonathanFingold** [comment]
PS. We need a better pipeline for getting UI fixes through from the C# SDK through Components into Composer nightlies, one that doesn't take two months.
