### ISSUE TITLE
Switch template sample does not use correct syntax.

### ISSUE THREAD

**Issue by anmolgandhi007** [MicrosoftDocs/composer-docs#122]
Before SWITCH syntax there is a (-) missing under the heading [Conditional response template](https://docs.microsoft.com/en-us/composer/concept-language-generation) in sub-heading Switch.

Reference - 
https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0#switch-template

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8fd4a76-f071-477d-57b4-fd746c1c682e
* Version Independent ID: 3947e8f1-28bc-d8e3-daeb-b8522317700b
* Content: [Language generation in Bot Framework Composer - Bot Composer](https://docs.microsoft.com/en-us/composer/concept-language-generation)
* Content Source: [composer-docs/concept-language-generation.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/concept-language-generation.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out. The fix with the correct content should go live shortly.

**Comment by emgrol** [comment]
Closing now that the fix has been merged and is live.
