### ISSUE TITLE
"Adding cards" has incorrect information.

### ISSUE THREAD

**Issue by dulfe** [MicrosoftDocs/composer-docs#123]
In the "Adding Cards" section, step 2 indicates:

_"In the Properties pane on the left, select **Switch to response editor**. Replace the existing response with the following ThumbnailCard template:"_

The properties pane is on the RIGHT and if we copy-and-paste the code:
```
[ThumbnailCard
    title = Weather 
    text = The temperature at ${user.postalcode} is ${dialog.fahrenheit}&deg;
]
```

into that "**Response Editor**", it will show its contents as TEXT, not a card.

![image](https://user-images.githubusercontent.com/12144048/116434691-a2445200-a818-11eb-9802-6f1560413030.png)

If we instead do it in the "**Code Editor**", It works, but cannot be switched back to "Response Editor"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9be9f7b5-d020-0b8d-a282-67d60d4edf4b
* Version Independent ID: 19ae4e68-6c6b-8b84-a113-e3b7481e530d
* Content: [Tutorial: Add cards to a bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-cards)
* Content Source: [composer-docs/tutorial/tutorial-cards.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-cards.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Hi @dulfe, is there any chance you have tested this recently? I recreated the bot and didn't run into this issue.

**Comment by dulfe** [comment]
@emgrol I just download Composer 2.0 which was released about a week ago (I was using Composer v1 when I created the issue) and it works!

**Comment by emgrol** [comment]
@dulfe I'm glad to hear it! Closing now that all aspects of the issue have been resolved.
