### ISSUE TITLE
Looks like a ) that should not be in the value

### ISSUE THREAD

**Issue by DataSnowman** [MicrosoftDocs/composer-docs#124]
[Enter feedback here]

In the Set properties pane on the right, perform the following steps to get the necessary weather values:

Set dialog.weather property.
Select the Add button.
In the Property field, enter dialog.weather.
In the Value field, enter: =dialog.api_response.content.weather[0].description).

please drop the periods on the end of the sentences enter dialog.weather instead of dialog.weather.

Also 

=dialog.api_response.content.weather[0].description).

should be
=dialog.api_response.content.weather[0].description

Don't need the closing ) or .

The ) causes an error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc39a432-6924-dbfd-42b8-bab7df273e77
* Version Independent ID: acfd500f-7115-aea9-a99b-c67764f61119
* Content: [Tutorial: Add actions to a bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-get-weather)
* Content Source: [composer-docs/tutorial/tutorial-get-weather.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-get-weather.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing these typos out. Closing this issue because they were fixed in the last live release.
