### ISSUE TITLE
Composer\plugins\localPublish\src\localPublish\src\index.js does not exist anymore

### ISSUE THREAD

**Issue by frarin-zz** [MicrosoftDocs/composer-docs#125]
The file Composer\plugins\localPublish\src\localPublish\src\index.js does not exist anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd89c358-c073-9d98-3465-42bc8bc3da91
* Version Independent ID: 486b07ca-44a3-508e-7a00-28c773bc996b
* Content: [Host Composer as a web app - Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-host-composer)
* Content Source: [composer-docs/how-to-host-composer.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-host-composer.md)
* Service: **bot-composer**
* GitHub Login: @benbrown
* Microsoft Alias: **kamrani**

**Comment by frarin** [comment]
I have to add also this: **error Command "build:plugins" not found.**

**Comment by emgrol** [comment]
Closing due to age. If this is still an issue, please re-open this request with updated details.
