### ISSUE TITLE
Command 'Sudo' not found

### ISSUE THREAD

**Issue by frarin** [MicrosoftDocs/composer-docs#127]
[Enter feedback here]

Please fix the **S**udo command for the nginx web server command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd89c358-c073-9d98-3465-42bc8bc3da91
* Version Independent ID: 486b07ca-44a3-508e-7a00-28c773bc996b
* Content: [Host Composer as a web app - Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-host-composer)
* Content Source: [composer-docs/how-to-host-composer.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-host-composer.md)
* Service: **bot-composer**
* GitHub Login: @benbrown
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out. We removed `sudo` from the commands and added a note in the linked PR.

Closing now that changes are merged.
