### ISSUE TITLE
when use chinese it be Garbled code

### ISSUE THREAD

**Issue by zhangtingwz** [MicrosoftDocs/composer-docs#128]
nice 2 meet u 
i`m an student
when i use send an http requet to [http://wthrcdn.etouch.cn/weather_mini?city=北京]  bot become like 
`{

“statusCode”: 200,

“reasonPhrase”: “OK”,

“headers”: {

“Server”: “Tengine/2.3.2”,

“Date”: “Tue, 18 May 2021 06:19:53 GMT”,

“Connection”: “keep-alive”,

“Access-Control-Allow-Headers”: “*”,

“Access-Control-Allow-Methods”: “*”,

“Access-Control-Allow-Origin”: “*”,

“Cache-Control”: “must-revalidate, max-age=300”,

“Age”: “155”,

“X-Via-Ucdn”: “HIT by 60.163.132.210, HIT by 180.97.190.59”

},

“content”: “\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0000\u0000��]K�P\u0018\u0007�R�z\u0017�$�\u0011��]\u0017�t’^\f��`3�D�\b�[\t���+\u0003\u0011�����d$}��9nW}��P�fa!]>���;���ce\u00160q��̇9V�\n\u001c�\u0001�\u0013U�H���>H\u0002\u0002�\u0003�\u001f�歊\u0006�\u0015\u0007��I�t?�3��b6��\n���ԇEk\n�6�\u0012��ƪgk۽���#����Ĺ�\u001cZ\u0007�֕��A�\u0000���XA��kw��P����\f\u0018��Z�YZa�EO��E!\u0018���Y��^\u0010\u000b��0�\u000e<��o�\u0015iC\S���ܟe �\u00154����ڜ�v�U����W2k�\u0019\u00055�(g�\n�?(�e�@ۍ��/�]��b��b��\u0000\u0002+\u001e�!˔���)R+�TƐ��\u0002l]�#�xx2�)8�\u0018�4:�\u001b��(�ţ豃2%�ц�,���q�-���Gy����\u001c��[H2+G$�P$I\u0012��%\u001f\u001e��\u0001�\u000f\u0012\nZ:�\u0003\u0000\u0000”

}`

then i use postman it be 
![image](https://user-images.githubusercontent.com/26179617/118602073-c924f100-b7e4-11eb-8170-059611e8bd15.png)

this is my bot 
![image](https://user-images.githubusercontent.com/26179617/118602190-f2458180-b7e4-11eb-9f3d-1911fd2b5838.png)

please answer for me ,thank you very much 3000 again

**Comment by hibrenda** [comment]
@danieladu may take a look.

**Comment by Danieladu** [comment]
Sure. I seems that the response is wrapped with GZip format, but `HttpClient` does not handler it. I have create a draft PR to try to solve it.

**Comment by boydc2014** [comment]
@JonathanFingold Can you help transfer this to SDK repo so that we get a triage on priority on this fix?

**Comment by JonathanFingold** [comment]
I'll close this out after the PR is merged into the SDK repo.

**Comment by JonathanFingold** [comment]
Thanks for reaching out. We've passed this feedback along to the SDK team and they have this work in queue. Since we can't address this directly in docs, we are closing the issue. If you need to, please reopen.
