### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by anmolgandhi007** [MicrosoftDocs/composer-docs#129]
Under the heading - Generate a skill manifest and publish your skill
Point 6 - Your bot needs to be provisioned and should have a publishing profile *creeated* in order to make it a skill.
Correction - created
![image](https://user-images.githubusercontent.com/25576582/119050017-eb825e80-b9de-11eb-8384-e6a3ee94a008.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae2b3954-046f-f4d6-dabd-9b9b94d181f8
* Version Independent ID: 8ab48d45-2148-e261-a7db-62bb975e7de3
* Content: [Publish a skill to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-skill?tabs=v2x)
* Content Source: [composer-docs/how-to-publish-skill.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-skill.md)
* Service: **bot-composer**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out, the typo fix should go live soon.

**Comment by emgrol** [comment]
Closing now that the fix has been merged and is live.
