### ISSUE TITLE
Test the bots locally section contains errors

### ISSUE THREAD

**Issue by gremlin529** [MicrosoftDocs/composer-docs#130]
In the  Test the bots locally section there are a few potential errors mainly in section 3a. Most of these are minor, one is potentially quite confusing

1. First the Welcome is wrong, it never tells you to update the text to "Welcome tot he EchoBot sample" so the text you see is actually "Welcome to your bot"
2. The second one is potentially more confusing when you first enter "Echo" the echo skill as it's coded does not start with "You said 'echo'" it won't echo until you type something else

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9863a83d-f2fa-5b20-c22e-ee9cbd1d727c
* Version Independent ID: 986de81e-23d5-5c22-4b9d-1967e3c338c1
* Content: [How to create and test a local skill -  Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-export-a-skill?tabs=v2x)
* Content Source: [composer-docs/how-to-export-a-skill.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-export-a-skill.md)
* Service: **bot-composer**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@gremlin529 The UI may have changed after the article was written. Investigating.

**Comment by JonathanFingold** [comment]
@gremlin529 I identified a few problems with my original logic and am updating the article and screenshots. I need to validate that the other two articles that logically follow this one still work as described, and then I'll publish the fix.

A couple quick notes (which are making their way into the updated articles):
- The greeting is triggered by a conversationUpdate activity, which the skill bot only receives if it is started as a root bot.
- I'm adding a "startSkill" event trigger to the skill, to allow for greeting behavior when it is started from another bot.
- The root bot needs to set **Activity processed** to true and send a "startSkill" event when it connects to the skill.

**Comment by JonathanFingold** [comment]
@gremlin529 I've run into technical difficulties in the publishing the skill step. Will keep you posted.

**Comment by JonathanFingold** [comment]
@gremlin529 I'll be updating these articles in July.

**Comment by JonathanFingold** [comment]
Instructions should be correct now.
