### ISSUE TITLE
change the code in Validation

### ISSUE THREAD

**Issue by rvinothrajendran** [MicrosoftDocs/composer-docs#131]
The code length(this.value) == 5  is wrong one , It should be length(string(this.value)) == 5 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce92ad12-27d2-3e3c-5a25-122cfc002837
* Version Independent ID: 52b6a9f0-2bf1-56e1-4044-54b89e69b81e
* Content: [Ask for user input - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input?tabs=v2x#prompt-settings-and-validation)
* Content Source: [composer-docs/how-to-ask-for-user-input.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-ask-for-user-input.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
@rvinothrajendran Thank you. Made the [update](https://github.com/MicrosoftDocs/composer-docs-pr/pull/556), should be live soon.
