### ISSUE TITLE
Issue in building weather bot using openweather api following tutorial

### ISSUE THREAD

**Issue by AnantMishra30** [MicrosoftDocs/composer-docs#132]
Getting error while building the weather bot following the tutorial.

Error Trace:

{
  "type": "trace",
  "timestamp": "2021-05-26T16:14:39.237Z",
  "serviceUrl": "http://localhost:63420",
  "channelId": "emulator",
  "from": {
    "id": "638d28d0-be3d-11eb-8342-11b5159f4fa1",
    "name": "Bot",
    "role": "bot"
  },
  "conversation": {
    "id": "63903610-be3d-11eb-b04e-0fc9cd02e48d|livechat"
  },
  "recipient": {
    "id": "eb45e2f1-76cf-4aa1-b49f-2c418fb00519",
    "role": "user"
  },
  "locale": "en-US",
  "replyToId": "77318a70-be3d-11eb-b04e-0fc9cd02e48d",
  "label": "TurnError",
  "valueType": "https://www.botframework.com/schemas/error",
  "value": {
    "name": "DialogContextError",
    "message": "DialogStateManager.getValue: a scope of 'json' wasn't found.",
    "dialogContext": {
      "activeDialog": "HttpRequest[GET =`https://api.openweathermap.org/data/2.5/weather?zip=${user.postalcode},us&units=imperial&appid=3f50cf32936a5af0c8e36cc57199859d`]",
      "parent": "getWeather",
      "stack": [
        {
          "id": "ActionScope[SendActivity[${SendActivity_JFJPxX()}],TextInput[A...727037699]",
          "state": {
            "offset": 2
          }
        },
        {
          "id": "HttpRequest[GET =`https://api.openweathermap.org/data/2.5/weather?zip=${user.postalcode},us&units=imperial&appid=3f50cf32936a5af0c8e36cc57199859d`]",
          "state": {}
        }
      ]
    }
  },
  "name": "OnTurnError Trace",
  "id": "78b59260-be3d-11eb-b04e-0fc9cd02e48d",
  "localTimestamp": "2021-05-26T21:44:39+05:30"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc39a432-6924-dbfd-42b8-bab7df273e77
* Version Independent ID: acfd500f-7115-aea9-a99b-c67764f61119
* Content: [Tutorial: Add actions to a bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-get-weather?tabs=v2x)
* Content Source: [composer-docs/tutorial/tutorial-get-weather.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-get-weather.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Hi @AnantMishra30, I recreated the weather bot and tested it in the Emulator with no issues. Adding the support label since this isn't a docs issue.

**Comment by erhopf** [comment]
@AnantMishra30 - I tested this tutorial yesterday and it seems to be working in Composer v2.0. Can you upgrade to the latest version of Composer with the latest version of the Tutorial and let us know if you still have an issue. 

I'm going to close this issue. If you need to please, reopen.
