### ISSUE TITLE
Just few minor typos

### ISSUE THREAD

**Issue by cdavilarios** [MicrosoftDocs/composer-docs#133]
[Enter feedback here]
This command:
wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.debsudo dpkg -i packages-microsoft-prod.deb

Should be:
wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \\
sudo dpkg -i packages-microsoft-prod.deb

This changes:
location / {
          # First attempt to serve request as file, then
          # as directory, then fall back to displaying a 404.
          proxy_pass http://127.0.0.1:3000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
}

Should be:
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

And this command: 
pm2 start npm --name composer – start

Should be:
pm2 start npm --name composer -- start

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd89c358-c073-9d98-3465-42bc8bc3da91
* Version Independent ID: 486b07ca-44a3-508e-7a00-28c773bc996b
* Content: [Host Composer as a web app - Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-host-composer)
* Content Source: [composer-docs/how-to-host-composer.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-host-composer.md)
* Service: **bot-composer**
* GitHub Login: @benbrown
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out. A fix should go live shortly.

**Comment by JonathanFingold** [comment]
Fix is merged
