### ISSUE TITLE
Wrapper class extension method "CastTo" is showing error

### ISSUE THREAD

**Issue by sanketdixit2013** [MicrosoftDocs/composer-docs#134]
I have followed the steps mentioned in the documentation and created a "BookingDialogWrapper" class with the code provided in the documentation. The issue is that the extension method which is used for casting **options.CastTo<BookingDetails>()** is giving an compile time error as follows:

**'object' does not contain a definition for 'CastTo' and no accessible extension method 'CastTo' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)**

Also the documentation says we only need the three files **Dialogs\BookingDialog.cs**,  **Dialogs\DateResolverDialog.cs** and **FlightBookingRecognizer.cs** but I see a dependency for **BookingDetails.cs** class as well. Even after adding this class I get the above mentioned error.

Am I doing something wrong here as I have followed all the instructions given in the documentation but fail to compile the code?
Please help.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fb946c7-8e39-c64c-667d-a4edd7892c16
* Version Independent ID: 06fdee5b-6fe7-212a-d604-f97efce088f7
* Content: [Migrating an v4 SDK bot to Composer - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-migrate-a-bot-to-composer)
* Content Source: [composer-docs/how-to-migrate-a-bot-to-composer.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-migrate-a-bot-to-composer.md)
* Service: **bot-composer**
* GitHub Login: @garypretty
* Microsoft Alias: **gapretty**

**Comment by sanketdixit2013** [comment]
Hello, May I know by when can this issue will be assigned and looked into?

**Comment by garypretty** [comment]
Thanks for raising this @sanketdixit2013.  The doc is missing a step, which is adding an extension class with the CastTo method. Please add a file to your project called Extensions.cs and use the following code (altering the namespace appropriately).

You're also right that you need the model file BookingDetails.cs, we will amend the doc for these two points.

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;

namespace YourNamespace
{
    public static class Extensions
    {
        public static T CastTo<T>(this object obj)
        {
            if (obj is T asT)
            {
                return asT;
            }
            else if (obj is JObject asJobject)
            {
                // If types are not used by storage serialization, and Newtonsoft is the serializer
                // the item found can be a JObject.
                return asJobject.ToObject<T>();
            }
            else if (obj is JArray asJarray)
            {
                // If types are not used by storage serialization, and Newtonsoft is the serializer
                // the item found can be a JArray.
                return asJarray.ToObject<T>();
            }
            else if (obj == null)
            {
                return default(T);
            }
            else
            {
                throw new InvalidOperationException("Data is not in the correct format for casting.");
            }
        }
    }
}

```

**Comment by sanketdixit2013** [comment]
Thanks @garypretty the sample is working now.

**Comment by JonathanFingold** [comment]
@garypretty - Is there any reason not to just change the [CastTo](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/Extensions.cs) extension method from internal to public?

**Comment by JonathanFingold** [comment]
Doc issue resolved. Should be live soon.
