### ISSUE TITLE
Missing Debug a custom action section

### ISSUE THREAD

**Issue by OliverZ** [MicrosoftDocs/composer-docs#135]
Missing _Debug a custom action_ section. The information is not documented anywhere else. In the previous docs for Composer 1.x it was mentioned to: 

> In the Attach to Process window, select Microsoft.BotFramework.Composer.WebApp.exe from the
> Available processes section. Select Attach.

But the `Microsoft.BotFramework.Composer.WebApp.exe` does not exist when using Composer 2.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b45a275f-7b99-3611-589c-76774e23b35f
* Version Independent ID: 5c85f403-d998-ff31-a08e-6bb9d3a8cdb9
* Content: [Create custom actions - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions)
* Content Source: [composer-docs/how-to-create-custom-actions.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-create-custom-actions.md)
* Service: **bot-composer**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by JonathanFingold** [comment]
Following up with a subject matter expert.

**Comment by OliverZ** [comment]
Thank you. The problem still exists. I tried it today with Composer 2.1.1.

**Comment by emgrol** [comment]
Closing due to age. If this is still an issue, please re-open this request with updated details.
