### ISSUE TITLE
Not enough info on the JSON nodes when publishing on existing resources 

### ISSUE THREAD

**Issue by geo-msft** [MicrosoftDocs/composer-docs#136]
[Enter feedback here]

I do not see the values required in the JSON publish profile explained somewhere: 

{
  "name": "",
  "environment": "dev",
  "tenantId": "",
  "hostname": "",
  "runtimeIdentifier": "win-x64",
  "resourceGroup": "",
  "botName": "",
  "subscriptionId": "",
  "region": "",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "",
      "connectionString": ""
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "",
      "authKey": "",
      "databaseId": "botstate-db",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "",
      "container": ""
    },
    "luis": {
      "authoringKey": "",
      "authoringEndpoint": "",
      "endpointKey": "",
      "endpoint": "",
      "region": "westus"
    },
    "qna": {
      "subscriptionKey": "",
      "endpoint": ""
    },
    "MicrosoftAppId": "",
    "MicrosoftAppPassword": ""
  }
}

Some of them are intuitive, some others are not. 

Example: what do "name" and "hostname" refer to? 
For the QnA maker, where do we take these values from: 

 "subscriptionKey": "",
 "endpoint": ""

A step by step on how to populate each value in this JSON would be very useful. 

I refer to the publish on existing Azure resources. 

I am sorry if I missed them and they are somewhere well explained. If they are indeed, please feel free to point me to that resource. Thank you for your time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot?tabs=v2x)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Closing due to age. If this is still an issue, please re-open this request with updated details.
