### ISSUE TITLE
Download the installer link is hard to find

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/composer-docs#137]
The link to download the actual installer on this page is very hard to find. It should be moved out from the list of prereq's and made significantly more prominent.

**Comment by darrenj** [comment]
https://docs.microsoft.com/en-gb/composer/install-composer?WT.mc_id=Portal-fx#install-composer-as-a-desktop-application

This is linked to from the ABS portal so gets a lot of traffic. Are there examples we can pull from that have visuals/images of the OS versions to make them more prominent and obvious?

**Comment by JonathanFingold** [comment]
@clearab Which page are you referring to? I'll see what I can do.

**Comment by clearab** [comment]
Hrm, I wonder why our docs repo doesn't link to the page correctly when opening an issue. That is the right article - I added @darrenj as a reviewer as well.

**Comment by clearab** [comment]
I must have clicked the wrong button - did some testing and the metadata is getting added on other issues.

**Comment by JonathanFingold** [comment]
Fixed by Darren's PR.
