### ISSUE TITLE
The Image under Hand off to admin section is not visible in dark mode theme

### ISSUE THREAD

**Issue by RohitMungi-MSFT** [MicrosoftDocs/composer-docs#138]
The image under [Hand off to admin](https://docs.microsoft.com/en-us/composer/how-to-publish-bot?tabs=v2x#hand-off-to-an-administrator) is not visible properly if users are using dark mode in their browsers. Can this be made more accessible?

![image](https://user-images.githubusercontent.com/46958063/121682610-ec884680-cad9-11eb-885b-5580da661cb4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot?tabs=v2x#hand-off-to-an-administrator)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out. Closing this now that the image fix has been merged.
