### ISSUE TITLE
How to configure bot with existing resources in json format not explained properly thus having a problem in publishing the skill and the bot

### ISSUE THREAD

**Issue by bhagyesh2000** [MicrosoftDocs/composer-docs#139]
Have not properly explained how to fill json format for pre existing resources to be configured with the new bot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae2b3954-046f-f4d6-dabd-9b9b94d181f8
* Version Independent ID: 8ab48d45-2148-e261-a7db-62bb975e7de3
* Content: [Publish a skill to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-skill?tabs=v2x)
* Content Source: [composer-docs/how-to-publish-skill.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-skill.md)
* Service: **bot-composer**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@bhagyesh2000 - I'll be updating all the skills articles for a refresh mid July, and I make sure to add more information to this section. Is there a particular setting you need help with?

**Comment by bhagyesh2000** [comment]
I selected the option of creating new resources and thus published the bot on Azure
