### ISSUE TITLE
Links to c# and node.js are broken

### ISSUE THREAD

**Issue by MACEL94** [MicrosoftDocs/composer-docs#143]
Links to c# and node.js are broken in this docs page
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdf54a88-60d1-0f93-1b95-2a1adddaf51c
* Version Independent ID: 6045ccbf-e79c-61b8-59ac-61dec2bd3f82
* Content: [Introduction to Bot Framework Composer  - Bot Composer](https://docs.microsoft.com/en-us/composer/introduction?tabs=v2x)
* Content Source: [composer-docs/introduction.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/introduction.md)
* Service: **bot-composer**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by JonathanFingold** [comment]
@MACEL94 - thanks for spotting this I'll try to get a fix in this week. There is also a misformatted link on the same line. :(
![image](https://user-images.githubusercontent.com/35047199/123646631-3e201900-d7dc-11eb-8f27-b77bc32d42a1.png)

**Comment by JonathanFingold** [comment]
Fixes should go live early this week.
