### ISSUE TITLE
Latest(?) Visual C++ Redistributable for VS needed to build Bot Framework Composer on Windows

### ISSUE THREAD

**Issue by heinrich-ulbricht** [MicrosoftDocs/composer-docs#144]
Following the build instructions in a clean and (according to the instructions) prepared Azure VM running Windows 10 21H1 I got an error.

Running `yarn startall` showed this error message:

```
yarn run v1.22.5
$ yarn start
$ cross-env NODE_ENV=production PORT=3000 yarn start:server
$ yarn workspace @bfc/server start
$ node --max-http-header-size=16000 build/init.js
internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\heu\00_Repos\BotFramework-Composer\Composer\node_modules\orchestrator-core\orchestrator-core.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\heu\00_Repos\BotFramework-Composer\Composer\node_modules\@microsoft\bf-orchestrator\lib\labelresolver.js:14:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: C:\Program Files (x86)\Yarn\lib\cli.js start
Directory: C:\Users\heu\00_Repos\BotFramework-Composer\Composer\packages\server
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Only after installing the (as of writing this) latest Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 from [here](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) the error disappeard. This information is missing in the prerequisites.

(Hat tip to 'programmer dreamer' on [StackOverflow](https://stackoverflow.com/a/65970204/56658).)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9c3beea-362b-4545-4b68-6a8ffe3f7dc1
* Version Independent ID: a41bf8ab-a9ae-81d6-7f4b-3b08ea5773cb
* Content: [Build Bot Framework Composer from source (Node.js)](https://docs.microsoft.com/en-us/composer/build-composer-from-source)
* Content Source: [composer-docs/build-composer-from-source.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/build-composer-from-source.md)
* Service: **bot-composer**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by JonathanFingold** [comment]
The required version is v14.28 or later, and x64 or x32 only (ARM is not yet supported). We recommend downloading the latest vcredist (x64) from [The latest supported Visual C++ downloads](https://support.microsoft.com/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0).

I'll add this information to the article.
