### ISSUE TITLE
Wrong documentation for adding a customaction

### ISSUE THREAD

**Issue by lukashoferdev** [MicrosoftDocs/composer-docs#146]
I tested to add a custom action and I think there is an error in the documentation. 
In my opinion the component name should be MultiplyDialog and not CustomAction.MulitplyDialog.

"runtimeSettings": {
   "components": [
      {
         "name": "MultiplyDialog"
      }
   ]
}

Please update, thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b45a275f-7b99-3611-589c-76774e23b35f
* Version Independent ID: 5c85f403-d998-ff31-a08e-6bb9d3a8cdb9
* Content: [Create custom actions - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions#feedback)
* Content Source: [composer-docs/how-to-create-custom-actions.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-create-custom-actions.md)
* Service: **bot-composer**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by clearab** [comment]
Fixed in: https://github.com/MicrosoftDocs/composer-docs-pr/pull/591

**Comment by JonathanFingold** [comment]
Changes are live.
