### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by managedcoder** [MicrosoftDocs/composer-docs#147]
[Enter feedback here]
In reading the doc on this page: https://docs.microsoft.com/en-us/composer/how-to-create-packages...

The link "extending your bot with code" in the "Components in packages" section is broken (404).  That broken link is pointing to https://docs.microsoft.com/en-us/docs/extending-with-code.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5c8eb1-7cdd-d698-7b7f-52d1d1d8007d
* Version Independent ID: ba8ce385-ff98-0bf9-7bc5-d9a53b22c5cb
* Content: [Create and share packages - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-create-packages)
* Content Source: [composer-docs/how-to-create-packages.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-create-packages.md)
* Service: **bot-composer**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by clearab** [comment]
@JonathanFingold correct link should be: https://docs.microsoft.com/composer/concept-extend-with-code

**Comment by mmiele** [comment]
The link has been fixed in the current documentation.
