### ISSUE TITLE
Link to README.md not points to the wrong place so non-contributors can't see README contents 

### ISSUE THREAD

**Issue by managedcoder** [MicrosoftDocs/composer-docs#148]
[Enter feedback here]

The link in the sentence below from the [User Interface](https://docs.microsoft.com/en-us/composer/concept-extension#user-interface) section should point to [this url ](https://github.com/microsoft/BotFramework-Composer/tree/main/extensions/sample-ui-plugin), not the actual [README.md](https://github.com/microsoft/BotFramework-Composer/edit/main/extensions/sample-ui-plugin/README.md) file so that non-congributors like myself can see the README.

The way it is now, as a non-contributor, when I click the link I don't see the contents of the README.md page but instead I see a message that says, "You need to fork this repository to propose changes." as can be seen in the screen grab below.  Dropping the README.md part of the URL and pointing to the "sample-ui-plugin" folder will render the README.md as expected

"A detailed set of explanation, documentation, and examples are here"

![image](https://user-images.githubusercontent.com/17769186/124297636-456f5b80-db29-11eb-8383-548ac8958ba1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ac8e2eb-23cd-ebf7-e9af-9af17de69e0e
* Version Independent ID: 5908cea5-066a-48d2-a8e3-c3fd8fca0147
* Content: [Extensions in Bot Framework Composer](https://docs.microsoft.com/en-us/composer/concept-extension)
* Content Source: [composer-docs/concept-extension.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/concept-extension.md)
* Service: **bot-composer**
* GitHub Login: @cwhitten
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Closing now that the fix has been merged.
