### ISSUE TITLE
Templates link broken

### ISSUE THREAD

**Issue by tomwildes-soulmachines** [MicrosoftDocs/composer-docs#149]
Templates link (https://docs.microsoft.com/en-us/composer-docs/concept-templates.md) is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e19acb-a260-3ca0-0f10-c28ba0ab5a5b
* Version Independent ID: 58baff59-db7f-cb6a-dc23-fd267e786c37
* Content: [Create your first bot - Bot Composer](https://docs.microsoft.com/en-us/composer/quickstart-create-bot?tabs=v2x)
* Content Source: [composer-docs/quickstart-create-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/quickstart-create-bot.md)
* Service: **bot-composer**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Closing now that the fix has been merged.
