### ISSUE TITLE
address for HTTP call should be followed by a "copy" control, not a "go to page" control

### ISSUE THREAD

**Issue by mewa1024** [MicrosoftDocs/composer-docs#150]
In this step:

![image](https://user-images.githubusercontent.com/39317542/125361245-e88e5500-e321-11eb-81fd-dfae01da26b3.png)

The icon after the http address should copy, not navigate.

If you navigate, your browser could change the string from this:

> http://api.openweathermap.org/data/2.5/weather?zip=${user.postalcode},us&appid=Your_API_Token

to this (changing the curly braces into **%7B** and **%7D**):

> http://api.openweathermap.org/data/2.5/weather?zip=$%7Buser.postalcode%7D,us&appid=Your_API_Token

If you then copy in the URL with the %7B and %7D into your bot, it will not send the user.postal code and fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc39a432-6924-dbfd-42b8-bab7df273e77
* Version Independent ID: acfd500f-7115-aea9-a99b-c67764f61119
* Content: [Tutorial: Add actions to a bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-get-weather?tabs=v2x)
* Content Source: [composer-docs/tutorial/tutorial-get-weather.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-get-weather.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
We're actively working on this article and this should be fixed in our next release.
