### ISSUE TITLE
Missing step on changing Recognizer Type

### ISSUE THREAD

**Issue by lijithomas2020** [MicrosoftDocs/composer-docs#151]
Connecting to Cancel/ Help dialog instructions is missing a step. Before Adding a New Trigger (for Cancel/ Help), the Recognizer Type on the root bot should be set to "Regular Expression Recognizer". The default is Default Recognizer. If this is not done before adding a new Trigger - it will not allow the user to input a Regex (as shown in the figure, on this page).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e6663c-4d8c-5c93-ae66-8b556af3ad4d
* Version Independent ID: 5acb7423-f108-1bea-8888-ef620308e3f0
* Content: [Tutorial: Add help functionality to a bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-add-help?tabs=v2x)
* Content Source: [composer-docs/tutorial/tutorial-add-help.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-add-help.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
We're actively working on this article, and a fix will be out with the next release.
