### ISSUE TITLE
Needs correction

### ISSUE THREAD

**Issue by amitkumarcn** [MicrosoftDocs/composer-docs#152]
[Enter feedback here]
This page needs small correction.
Current line: The regular expression is written so that the bot will recognize the cancel trigger whenever a user responds with help, support, or advice.

It should be:
The regular expression is written so that the bot will recognize the help trigger whenever a user responds with help, support, or advice.

its a typo  i guess

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e6663c-4d8c-5c93-ae66-8b556af3ad4d
* Version Independent ID: 5acb7423-f108-1bea-8888-ef620308e3f0
* Content: [Tutorial: Add help functionality to a bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-add-help?tabs=v2x)
* Content Source: [composer-docs/tutorial/tutorial-add-help.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-add-help.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
We're actively working on this article, and a fix will be out with the next release.
