### ISSUE TITLE
little error in the formulaon this page

### ISSUE THREAD

**Issue by maurominella** [MicrosoftDocs/composer-docs#153]
Hi this page has an error in the code: in fact the number 
32,0 
in the formula for Farheneit degrees should be written as 
32.0

otherwise it reports the error "reference not set to an instance of the object".

Thanks

Mauro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc39a432-6924-dbfd-42b8-bab7df273e77
* Version Independent ID: acfd500f-7115-aea9-a99b-c67764f61119
* Content: [Tutorial: Add actions to a bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-get-weather?tabs=v2x#get-weather-report)
* Content Source: [composer-docs/tutorial/tutorial-get-weather.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-get-weather.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
We're actively working on this article, and a fix will be out with the next release.
