### ISSUE TITLE
Emulator always shows English bot

### ISSUE THREAD

**Issue by dinobrago** [MicrosoftDocs/composer-docs#157]
[Enter feedback here]

I implemented this sample using Spanish. It works in the web chat in Spanish and English depending on what language is the default in Composer. 

But in the emulator it remains in English regardless of what is chosen in Composer. 

Bot Framework Composwer v 2.1.0
Emulator version 4.13.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e3f9d9-a593-40a3-bd68-1235966cca23
* Version Independent ID: 6984f534-80f3-6bd8-0392-b1cedf86393a
* Content: [Multiple language support - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language)
* Content Source: [composer-docs/how-to-use-multiple-language.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-use-multiple-language.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out. We added information about updating your Emulator settings.

Closing now that changes are merged.
