### ISSUE TITLE
Emulator locale needs to be changed manually

### ISSUE THREAD

**Issue by dinobrago** [MicrosoftDocs/composer-docs#158]
The documentation should reflect that the emulator locale needs to be changed locally to see the added language. The web-chat changes automatically. The Emulator does not. 

1. Open the Bot Framework Emulator
2. Open the Settings tab.
3. Set your desired locale in the Locale field and click Save
4. Connect to the bot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e3f9d9-a593-40a3-bd68-1235966cca23
* Version Independent ID: 6984f534-80f3-6bd8-0392-b1cedf86393a
* Content: [Multiple language support - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language)
* Content Source: [composer-docs/how-to-use-multiple-language.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-use-multiple-language.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out. We added instructions in the linked PR.

Closing now that changes are merged.
