### ISSUE TITLE
Update name of the Trigger

### ISSUE THREAD

**Issue by Ahed-bahri** [MicrosoftDocs/composer-docs#159]
[Greeting trigger in Add language understanding data and conditions Section should be updated to **Goodbye** ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb60696-585d-ed05-075c-71de3b948572
* Version Independent ID: 129f51db-8840-05fb-527d-4eed2663d2f7
* Content: [Add LUIS to your bot - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-add-luis?tabs=v2x)
* Content Source: [composer-docs/how-to-add-luis.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-add-luis.md)
* Service: **bot-composer**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out. A fix has been added.
