### ISSUE TITLE
Orchestrator - Multi lingual support

### ISSUE THREAD

**Issue by vinaysopinti** [MicrosoftDocs/composer-docs#160]
[Enter feedback here]

How many languages does Orchestrator multilingual base model **pretrained.20210205.microsoft.dte.00.06.unicoder_multilingual.onnx** support ? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa4c3057-ca39-6ffe-6d85-4c72a8813530
* Version Independent ID: 49f54c52-f87e-6d1f-8dc2-6e8446423dcd
* Content: [Orchestrator - Bot Composer](https://docs.microsoft.com/en-us/composer/concept-orchestrator)
* Content Source: [composer-docs/concept-orchestrator.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/concept-orchestrator.md)
* Service: **bot-composer**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by emgrol** [comment]
@scheyal @davetcha Do you have any information about this?

**Comment by scheyal** [comment]
See documentation here: https://github.com/microsoft/botframework-sdk/blob/main/Orchestrator/docs/NLRModels.md#pretrained20210608microsoftdte0106intunicoder_multilingualonnx

**Comment by emgrol** [comment]
Closing now that the issue's been resolved.
