### ISSUE TITLE
incorrect syntax and instruction on Step 4

### ISSUE THREAD

**Issue by fitprotracker** [MicrosoftDocs/composer-docs#163]
the values are not aligned correctly. 

![image](https://user-images.githubusercontent.com/52284584/129460730-033bb5dc-793e-4e99-b60e-2c751ef71171.png)

to get it to work, this is the correct syntax for this to work

![image](https://user-images.githubusercontent.com/52284584/129460749-e748fac0-3b0a-4971-8d81-b1f055f7332c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c55e6920-2987-2b78-66b7-3dee92ab8689
* Version Independent ID: 5d9f5e75-ee25-cc5d-bdd5-594712badf63
* Content: [Tutorial: Improve intent recognition in your Composer bot with Language Understanding - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial-improve-intent-recognition-language-understanding?tabs=v2x)
* Content Source: [composer-docs/tutorial-improve-intent-recognition-language-understanding.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial-improve-intent-recognition-language-understanding.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this error out. We're working on a fix.

**Comment by emgrol** [comment]
Closing now that changes are merged.
