### ISSUE TITLE
Error in image on page

### ISSUE THREAD

**Issue by metkhoo** [MicrosoftDocs/composer-docs#164]
URL:
https://docs.microsoft.com/en-us/composer/tutorial-improve-intent-recognition-language-understanding

The image in "Using LUIS for entity extraction" item 4, showing "Set a property" is incorrect.  The image shows the Value to be 

postalcode

It should be 

=@postalcode

in line with the text of the paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c55e6920-2987-2b78-66b7-3dee92ab8689
* Version Independent ID: 5d9f5e75-ee25-cc5d-bdd5-594712badf63
* Content: [Tutorial: Improve intent recognition in your Composer bot with Language Understanding - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial-improve-intent-recognition-language-understanding?tabs=v2x)
* Content Source: [composer-docs/tutorial-improve-intent-recognition-language-understanding.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial-improve-intent-recognition-language-understanding.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out. A fix has been implemented and will go live shortly.
