### ISSUE TITLE
The customFunctions property doesn't work

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/composer-docs#166]
Trying to use the customFunctions setting as described in this document, I still receive a warning telling me to add the function to the customFunctions setting:

![image](https://user-images.githubusercontent.com/41968495/130517403-d4c0bc15-a9dd-43e8-ab00-0fda4010f68a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12abeb8c-355b-0134-b6e0-30e6824bd21f
* Version Independent ID: 8bc58e26-4a19-e440-aa33-8906098a19db
* Content: [Validate .lg and .lu files and expressions data - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-validate?tabs=v2x)
* Content Source: [composer-docs/how-to-validate.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-validate.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@v-kydela For this to work, you need to be using a custom run time. Emily will follow up, but this section might help: https://docs.microsoft.com/en-us/composer/concept-extension#runtime-templates

**Comment by emgrol** [comment]
Closing due to age. If this is still an issue, please re-open this request with updated details.
