### ISSUE TITLE
Bad Markdown link on this page

### ISSUE THREAD

**Issue by managedcoder** [MicrosoftDocs/composer-docs#167]
There is a Markdown link that isn't coded correctly.  Search for this text string to find it: "(Triggers)(#concept-events-and-triggers.md)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e68ad7f-b67a-aebb-d019-4e4e07234501
* Version Independent ID: 17a6eac3-ca69-928d-1dfa-3c61518e5475
* Content: [Create conversations with dialogs and Bot Framework Composer](https://docs.microsoft.com/en-us/composer/concept-dialog?view=azure-bot-service-4.0&tabs=v2x)
* Content Source: [composer-docs/concept-dialog.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/concept-dialog.md)
* Service: **bot-composer**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Thanks @managedcoder - a fix is in PR and should go live within a week.

**Comment by JonathanFingold** [comment]
I belatedly saw another bad bit of Markdown, which I'll fix presently.
