### ISSUE TITLE
Unclear text in QnA documentation

### ISSUE THREAD

**Issue by kostasvl** [MicrosoftDocs/composer-docs#168]
> A best practice is to set the confidence threshold for LUIS intent prediction and trigger QnA Maker through Intent event.

Do you mean  "...through **Unknown**Intent event.", perhaps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808c15b1-52e8-eda3-547a-037f7a74d094
* Version Independent ID: bb1f0f82-b57a-d7a8-e013-31692b22c593
* Content: [Add a QnA Maker knowledge base to your bot - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot?tabs=v2x)
* Content Source: [composer-docs/how-to-add-qna-to-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-add-qna-to-bot.md)
* Service: **bot-composer**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Closing due to doc changes.
