### ISSUE TITLE
Missing documentation about "settingsPrefix"

### ISSUE THREAD

**Issue by kostasvl** [MicrosoftDocs/composer-docs#169]
This page (and its sibling) could do with a mention of the "settingsPrefix" json property. Without it, an empty Configuration object is passed to BotComponent.ConfigureServices, with no feedback as to why. I had to decompile the code to figure this out :).  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b45a275f-7b99-3611-589c-76774e23b35f
* Version Independent ID: 5c85f403-d998-ff31-a08e-6bb9d3a8cdb9
* Content: [Create custom actions - Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions)
* Content Source: [composer-docs/how-to-create-custom-actions.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-create-custom-actions.md)
* Service: **bot-composer**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by emgrol** [comment]
Closing due to age. If this is still an issue, please re-open this request with updated details.

**Comment by devbynight** [comment]
Hi @kostasvl , I am facing this issue. Where should we add this setting?

**Comment by kostasvl** [comment]
Hi @devbynight. You need the settingsPrefix in appsettings.json:

![image](https://user-images.githubusercontent.com/17363218/188600118-8bf977de-312d-4804-8ca8-58411423a4e5.png)

I see there's an example there from the Orchestrator now, but maybe I wasn't using the Orchestrator back then, or I didn't make the connection, etc. There's no actual Orchestrator section in my appsettings.json anyway. Regardless, I still think the above documentation page should have a small paragraph to explain settingsPrefix.

Finally:

![image](https://user-images.githubusercontent.com/17363218/188601109-b0fdb43c-9912-435b-95ee-57888132ec26.png)

**Comment by devbynight** [comment]
Thanks @kostasvl
