### ISSUE TITLE
Tutorial mistakes

### ISSUE THREAD

**Issue by metkhoo** [MicrosoftDocs/composer-docs#170]
Hi
The page is very disappointing
https://docs.microsoft.com/en-us/composer/templates/enterprise-people-tutorial

ERROR 1: Wrong bot template in document
The page:
https://docs.microsoft.com/en-us/composer/templates/enterprise-people-tutorial
is clearly the "Enterprise People" tutorial but the text in section "Create your project in Composer", step 3 says :

3. Select Enterprise Calendar Bot

Surely this should be 
3. Select "Enterprise People Bot" and click "Next"

ERROR 2: Ambiguous instruction
Step 4:  in "Create your project in Composer" is ambiguous.  It says "... and Runtime type..."  How does the student know what to pick or the differences between them.  Since this is a "tutorial" you should tell the student the option to pick.

ERROR 3: Missing explanation
After finishing "Step 4" in "Create your project in Composer",  Composer will show the BOT and it will have ERRORS.  You don't mention this.  The Errors ar rleated to Setting up Langugage Understanding and there is a baloon saying "Continue setting up your development environment by adding LUIS keys."  There is no mention of this in the tutorial and following the instructions from Composer at this point will lead the student off into creating resources.  The tutorial needs to tell the student to ignore any messages and continue to "Provision Azure resources"

ERROR 4: Missing explanation
In "Provision Azure responses" it says "Create a publishing profile".  you have not told the student where to go to create the publishing profile.  Step 1 should say something like.:

In Composer, click on the main "Publish" icon on the navigator, select the checkbox next to the BOT you just created and in the "Publish target" select "Manager profiles"
In the "Publishing profile" tab, select the "add new" link.
Give your publishing profile a name and select your publishing target as "Publish bot to Azure".  Then click "Next"
For this tutorial, select "Create new resources" for the radio button on the left and click "Next"
Select your Azure Subscription, then Select "Create new" then give the new resource group a name.  
In the "App Service (Web App or Function)" select the operating system (typically windows).
"Name" will be the App Service name.  Enter this then select a region for the BOT and a region for LUIS (this has a restricted number of options).  Click "Next" to see the resources options screen then click "Next" to see a summary then "Create" to create the Azure resources.  It make take a while.

ERROR 5: Context is lost in the tutorial
For "Provision Azure resources" step 2 comes after the student has provisioined resources.  You have not told the student where to find the "Configure > Development Resources" options

The text should read something like:

With the resources created in Azrue, back in the Composer, open the "Configure > Developement Resources" ...

Click on "Set up Language Understand" button and select the "Radio" "Use existing resources".  Select your subscription and the resource from the resource group you created earlier.  Click "Next" then click "Done"

Click on "Set up QnA Maker" , then select the radio "Use existing resources".  Select your subscription then 
the resource created earlier Click "Next" then "Done"

Click the "Retrieve App ID" to retrieve the Azure App ID of the Azure resource just created

ERROR 6: Context change in "Using the Azure Portal"
I think the first step should be:
1. open the Azure Portal https://portal.azure.com then ....

ERROR 7: Ambiguous flow
In "Next Step" you provide too many options for the student.  You should either publish locally or publishh to Azure.   It seems that publishing to Azure should be the option here.

ERROR 8: Restating previous step
In the "Publish to Azure" section after "Next steps", you reiterate something that would have already been done.  This is confusing to the student.

ERROR 9: DOES NOT WORK - THE MOST IMPORTANT ONE
Even after following the instructions to the letter the Tutorial does not work.
The publishing error thrown up by BOT Composer V2.1.1. is:

"SyntaxError - Unexpected token u in JSON at position 0"

This is not the sort of quality tutorial that I have come to expect from Microsoft

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52929f3d-e53a-627a-9f18-cf4abc57dd6c
* Version Independent ID: 720e888d-7e2d-cb37-f445-7072cdf4f984
* Content: [Enterprise People Bot Template Tutorial - Bot Composer](https://docs.microsoft.com/en-us/composer/templates/enterprise-people-tutorial)
* Content Source: [composer-docs/templates/enterprise-people-tutorial.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/templates/enterprise-people-tutorial.md)
* Service: **bot-composer**
* GitHub Login: @lauren-mills
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for bringing this to our attention. Closing now that the fixes have been merged.

**Comment by emgrol** [comment]
Added fixes for errors 1-8. Adding the support label to get help with error 9.

**Comment by emgrol** [comment]
Closing due to age. If this is still an issue, please re-open this request with updated details.
