### ISSUE TITLE
"Error MultiplyDialog: Interface Microsoft.IDialog is not defined" when running update-schema.ps1

### ISSUE THREAD

**Issue by kh-frontier** [MicrosoftDocs/composer-docs#172]
Following the [How to create custom actions](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions) tutorial exactly, upon running the PowerShell script (with admin privileges and also ensuring my execution-policy allows for running unsigned scripts) I get the following result:

```
Running schema merge.
Finding component files
Parsing component .schema files
Merging component schemas
Error MultiplyDialog: Interface Microsoft.IDialog is not defined


*** Could not merge components ***
Schema merge failed. Restoring previous versions.
```

Is there a way to manually update the schema instead?

The MultiplyDialog project has the Microsoft.Bot.Builder.Dialogs.Adpative.Runtime dependency at the same version as my bot solution. The MultiplyDialog project is a Microsoft.NETCore.App version 3.1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b45a275f-7b99-3611-589c-76774e23b35f
* Version Independent ID: 5c85f403-d998-ff31-a08e-6bb9d3a8cdb9
* Content: [Create custom actions - Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions)
* Content Source: [composer-docs/how-to-create-custom-actions.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-create-custom-actions.md)
* Service: **bot-composer**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by emgrol** [comment]
Related issue: https://github.com/MicrosoftDocs/composer-docs/issues/135

**Comment by kh-frontier** [comment]
Extra info:

Tried to run the merge on the same project but on a different machine and the same error persists.

When I tried with a blank project I received a new error as seen below: 
```
Running schema merge.
Finding component files


Copying exported assets to imported
Schema merge failed. Restoring previous versions.
```

Looks like it's an issue with my project. Not sure why it's failing differently with a blank project either.

**Comment by emgrol** [comment]
Closing due to age. If this is still an issue, please re-open this request with updated details.
