### ISSUE TITLE
Any quickstart guide for Composer Extension Feature?

### ISSUE THREAD

**Issue by gitathrun** [MicrosoftDocs/composer-docs#175]
Hi, It is a great feature for developers to extend Composer IDE with customisation, but after reading through this page, I am not clear about following point:
1. Is there any quick start guide with snapshot that can lead developer to run and see the difference of an extension? such as the Sample-ui-plug example, directly show us the difference with/without of an extension?
2. There are different version of Composer, like downloaded windows app, mac app and web app version, I am wandering does this Composer extension feature works for all version or only the web app version? I have created a subdirectory "extension" in my windows app Composer and copy paste the Sample extension into the directory, but windows app Composer startup and there is no difference before/after, can anyone explain whether the Composer extension support all Composer version? and guide on how to setup?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ac8e2eb-23cd-ebf7-e9af-9af17de69e0e
* Version Independent ID: 5908cea5-066a-48d2-a8e3-c3fd8fca0147
* Content: [The extension APIs in Bot Framework Composer](https://docs.microsoft.com/en-us/composer/concept-extension)
* Content Source: [composer-docs/concept-extension.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/concept-extension.md)
* Service: **bot-composer**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Closing due to age. If this is still an issue, please re-open this request with updated details.
