### ISSUE TITLE
Why not link any document to this https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot?tabs=v2x#bots-with-language-understanding-luis-and-qna-maker

### ISSUE THREAD

**Issue by vvvhung** [MicrosoftDocs/composer-docs#176]
Reading to this and do not know how to do it. Should have a link to a relevant document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808c15b1-52e8-eda3-547a-037f7a74d094
* Version Independent ID: bb1f0f82-b57a-d7a8-e013-31692b22c593
* Content: [Add a QnA Maker knowledge base to your bot - Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot?tabs=v2x)
* Content Source: [composer-docs/how-to-add-qna-to-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-add-qna-to-bot.md)
* Service: **bot-composer**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Closing due to age. If this is still an issue, please re-open this request with updated details.
