### ISSUE TITLE
Download links for installers/pre-compiled Composer binaries are outdated

### ISSUE THREAD

**Issue by anishprasad01** [MicrosoftDocs/composer-docs#177]
The `aka.ms` links on the docs page for [downloading Composer](https://docs.microsoft.com/en-us/composer/install-composer?tabs=macos#download-composer) are stale and clicking them downloads version `2.0.0` instead of the latest version (`2.1.1` at time of writing). Seeing users coming in with issues on older versions. Perhaps updating the links or more prominently featuring a link to the Github releases page would rectify this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 668b24a1-8df0-579c-a656-cb1b8e63f5ea
* Version Independent ID: 14fd497a-8916-153d-5bc0-cfe65fab7c98
* Content: [Install Bot Framework Composer](https://docs.microsoft.com/en-us/composer/install-composer?tabs=windows)
* Content Source: [composer-docs/install-composer.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/install-composer.md)
* Service: **bot-composer**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing out these update links, a fix should go live shortly.
