### ISSUE TITLE
Sample code snippet is incorrect

### ISSUE THREAD

**Issue by rcabr** [MicrosoftDocs/composer-docs#179]
I discovered this by running this code after changing --CreateQnAResource to false, but the QnA resources were still deployed.

Sample code snippet is incorrect.  
1. "createAppInsights" should be prepended with "--".  
2. "--CreateQnAResource" should probably be "--createQnAResource" for consistency.

Original:
node provisionComposer.js --subscriptionId=<YOUR AZURE SUBSCRIPTION ID> --name=<YOUR RESOURCE NAME> --appPassword=<APP PASSWORD> --environment=<NAME FOR ENVIRONMENT DEFAULT to dev> --location=<LOCATION> --createLuisResource=true --createLuisAuthoringResource=true --createCosmosDb=false --createStorage=false createAppInsights=true --CreateQnAResource=true

Fixed:
node provisionComposer.js --subscriptionId=<YOUR AZURE SUBSCRIPTION ID> --name=<YOUR RESOURCE NAME> --appPassword=<APP PASSWORD> --environment=<NAME FOR ENVIRONMENT DEFAULT to dev> --location=<LOCATION> --createLuisResource=true --createLuisAuthoringResource=true --createCosmosDb=false --createStorage=false --createAppInsights=true --createQnAResource=true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bb54117-e12a-1d10-1bd2-633399847420
* Version Independent ID: 2c623b8d-d241-896a-3338-f6ea687283c0
* Content: [How to provision Azure resources for Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-provision-azure-resources)
* Content Source: [composer-docs/how-to-provision-azure-resources.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-provision-azure-resources.md)
* Service: **bot-composer**
* GitHub Login: @emgrol
* Microsoft Alias: **v-eolshefski**

**Comment by emgrol** [comment]
Closing now that the fix was published live.
