### ISSUE TITLE
Using proper are names instead of "left" and "right"

### ISSUE THREAD

**Issue by shahabhijeet** [MicrosoftDocs/composer-docs#180]
I am referring to the following link
https://docs.microsoft.com/en-us/composer/quickstart-create-bot#create-a-trigger-to-recognize-the-menu-intent
And on the second bullet point, it mentions "On the right, select the regular expression".
Isn't the correct word for the "right" is "properties area" of the composer.
Plus there is nothing called "regular expression" and what really confused is, step 1 says select your project first. I cannot select the root node, so how can I select the project?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e19acb-a260-3ca0-0f10-c28ba0ab5a5b
* Version Independent ID: 58baff59-db7f-cb6a-dc23-fd267e786c37
* Content: [Create your first bot in Bot Framework Composer](https://docs.microsoft.com/en-us/composer/quickstart-create-bot#feedback)
* Content Source: [composer-docs/quickstart-create-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/quickstart-create-bot.md)
* Service: **bot-composer**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for the feedback, we're updating the instructions to add clarity.

**Comment by emgrol** [comment]
Closing now that the updates are live.
