### ISSUE TITLE
LUIS authoring key link is not helpful

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/composer-docs#185]
Under the "Prerequisites" heading, the "LUIS authoring key" link does not explain how to create or access an authoring key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb60696-585d-ed05-075c-71de3b948572
* Version Independent ID: 129f51db-8840-05fb-527d-4eed2663d2f7
* Content: [Add language understanding in Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-add-luis?tabs=v2x)
* Content Source: [composer-docs/how-to-add-luis.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-add-luis.md)
* Service: **bot-composer**
* GitHub Login: @emgrol
* Microsoft Alias: **v-eolshefski**

**Comment by v-alarioza** [comment]
@BruceHaley Thanks for your report! Looks like that bullet was outdated, as LUIS keys are now managed by Azure LUIS resources. You can [follow these steps to create a LUIS resource from within Composer](https://docs.microsoft.com/en-us/composer/how-to-add-luis?tabs=v2x#update-luis-keys).
