### ISSUE TITLE
"Supported OS versions" link gets 404

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/composer-docs#186]
Under the "Prerequisites" heading, "Supported OS versions" is a bad link. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure from Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot?tabs=v2x)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @emgrol
* Microsoft Alias: **v-eolshefski**

**Comment by JonathanFingold** [comment]
@BruceHaley Link fix should be live sometime after noon.
