### ISSUE TITLE
Core bot Templates

### ISSUE THREAD

**Issue by cll670589** [MicrosoftDocs/composer-docs#187]
The bot templates do not work. 404 Error 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae86dcdb-fc63-630a-e45f-a90a41a9e328
* Version Independent ID: 60722ca6-74a1-8a73-4246-ffb352bb4814
* Content: [Templates available in Bot Framework Composer](https://docs.microsoft.com/en-us/composer/concept-templates#core-assistant-bot-template)
* Content Source: [composer-docs/concept-templates.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/concept-templates.md)
* Service: **bot-composer**
* GitHub Login: @emgrol
* Microsoft Alias: **v-eolshefski**

**Comment by emgrol** [comment]
Hi @cll670589, I tested the links on that page and all of them worked. I also test the templates in Composer and those work as well. Please file another issue if this persists for you.
