### ISSUE TITLE
Screenshot out of date

### ISSUE THREAD

**Issue by GraemeMalcolm** [MicrosoftDocs/composer-docs#191]
The dialog box when opening the bot in Composer is different to the one in the article. The options listed are:

- Create a new bot project
- Use an existing bot project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ac570c6-8532-b972-be2f-8e655ef34db2
* Version Independent ID: f01007a1-bf5b-92c6-7178-1963b052e5dc
* Content: [Create a bot in Azure - Bot Framework Composer](https://docs.microsoft.com/en-us/composer/quickstart-create-bot-with-azure)
* Content Source: [composer-docs/quickstart-create-bot-with-azure.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/quickstart-create-bot-with-azure.md)
* Service: **bot-composer**
* GitHub Login: @emgrol
* Microsoft Alias: **v-eolshefski**

**Comment by emgrol** [comment]
Closing due to doc changes.
