### ISSUE TITLE
Missing Visual C++ Redistributable as Prerequisites 

### ISSUE THREAD

**Issue by hannadeng** [MicrosoftDocs/composer-docs#193]
Failed to launch Bot Framework Composer without Visual C++ Redistributable, getting below error. 
Found the same issue at https://github.com/microsoft/BotFramework-Composer/issues/7964. 
After vc_redist.x64.exe package installed, the issue solved.

Suggest adding [vc_redist.x64.exe](https://aka.ms/vs/16/release/vc_redist.x64.exe) as a prerequisite in this article. 

![image](https://user-images.githubusercontent.com/103932765/163795543-656e7cd2-22dc-45ff-9757-1096050cb534.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 668b24a1-8df0-579c-a656-cb1b8e63f5ea
* Version Independent ID: 14fd497a-8916-153d-5bc0-cfe65fab7c98
* Content: [Install Bot Framework Composer](https://docs.microsoft.com/en-us/composer/install-composer?tabs=windows#download-composer)
* Content Source: [composer-docs/install-composer.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/install-composer.md)
* Service: **bot-composer**
* GitHub Login: @emgrol
* Microsoft Alias: **v-eolshefski**

**Comment by ramfattah** [comment]
Hey @hannadeng, thanks for reaching out.

According to [Redistributing Visual C++ Files](https://docs.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files?view=msvc-170#:~:text=you%20can%20use%20the%20redistributable%20packages%20installed%20by%20Visual%20Studio.) documentation, the redistributable packages are installed by Visual Studio.

Perhaps if it fails to launch Bot Framework Composer without Visual C++ Redistributable, we can add a note in the prerequisite to install the `vc_redist.x64.exe` package?

#

### Proposing the following changes:

> In some environments, Bot Framework Composer may not work correctly if Redistributing Visual C++ files have not been installed. Specifically, Bot Composer may not start or get stuck on the "Starting Server" message.

> In this case, please install additional [Visual C++ redistributable files](https://aka.ms/vs/16/release/vc_redist.x64.exe) to ensure that Composer starts successfully.

**Comment by hannadeng** [comment]
> Hey @hannadeng, thanks for reaching out.
> 
> According to [Redistributing Visual C++ Files](https://docs.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files?view=msvc-170#:~:text=you%20can%20use%20the%20redistributable%20packages%20installed%20by%20Visual%20Studio.) documentation, the redistributable packages are installed by Visual Studio.
> 
> Perhaps if it fails to launch Bot Framework Composer without Visual C++ Redistributable, we can add a note in the prerequisite to install the `vc_redist.x64.exe` package?
> 
> ### Proposing the following changes:
> > In some environments, Bot Framework Composer may not work correctly if Redistributing Visual C++ files have not been installed. Specifically, Bot Composer may not start or get stuck on the "Starting Server" message.
> 
> > In this case, please install additional [Visual C++ redistributable files](https://aka.ms/vs/16/release/vc_redist.x64.exe) to ensure that Composer starts successfully.

@ramfattah  Agree. It would be good adding the changes.

**Comment by JonathanFingold** [comment]
I'll update the docs. Thanks @ramfattah and @hannadeng .

**Comment by JonathanFingold** [comment]
Update should be live by tomorrow.
