### ISSUE TITLE
Add references to xxxExpression and schema docs

### ISSUE THREAD

**Issue by davhdavh** [MicrosoftDocs/composer-docs#194]
This page adequately explains how to make a very simple one, but it lacks references to figure out how to make a more complicated one. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b45a275f-7b99-3611-589c-76774e23b35f
* Version Independent ID: 5c85f403-d998-ff31-a08e-6bb9d3a8cdb9
* Content: [Create custom actions in Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions)
* Content Source: [composer-docs/how-to-create-custom-actions.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-create-custom-actions.md)
* Service: **bot-composer**
* GitHub Login: @emgrol
* Microsoft Alias: **v-eolshefski**

**Comment by JonathanFingold** [comment]
Added a couple more links. Changes should be visible later today.

**Comment by davhdavh** [comment]
Thanks.

I have dug a bit more into this subject, and I still think this article is vastly lacking in resources to continue making more complex custom actions.

1. The demo class inherits from `Dialog`, but there is no reference to that anywhere, or any explanations what other alternatives are available. It is also really weird that the schema says it `"$role": "implements(Microsoft.IDialog)",`, but the `Dialog` class does not in fact inherit from anything.
2. Nor is the flow really explained to make the developer understand what is actually going on.
3. How to read and write User state?
4. How to read and write Dialog state?
5. There should be a note that setting `runtimeSettings` is only when doing it in an external library.
6. The magic incantation for storing the result should really be explained `(dc.State.SetValue(this.ResultProperty.GetValue(dc.State), result);`).
7. Default values (also for enums)?
