### ISSUE TITLE
Recommend HTTPS instead of HTTP

### ISSUE THREAD

**Issue by dluc** [MicrosoftDocs/composer-docs#195]
URL: https://docs.microsoft.com/composer/tutorial-create-weather-bot#make-an-http-request

<img width="365" alt="image" src="https://user-images.githubusercontent.com/371009/164166057-b0297738-dffb-40d4-ba9a-d0adcd444388.png">

We should always recommend HTTPS where possible. Please replace:

> http://api.openweathermap.org/data/2.5/weather?zip=${user.postalcode},us&appid=YOUR_API_KEY

with

> https://api.openweathermap.org/data/2.5/weather?zip=${user.postalcode},us&appid=YOUR_API_KEY

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1636bda0-c8ee-5632-bb87-d7972f87e9d7
* Version Independent ID: c8ab72b1-f10a-b0a7-1424-d86a6978621a
* Content: [Tutorial: Create a weather bot with Bot Framework Composer](https://docs.microsoft.com/en-us/composer/tutorial-create-weather-bot)
* Content Source: [composer-docs/tutorial-create-weather-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial-create-weather-bot.md)
* Service: **bot-composer**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-eolshefski**

**Comment by emgrol** [comment]
Thanks for the recommendation, the fix should go live shortly.
