### ISSUE TITLE
Typo in Prerequisites section - "genertion" missing an 'a'

### ISSUE THREAD

**Issue by acwwat** [MicrosoftDocs/composer-docs#196]
There is a typo in the first item under **Prerequisites** section on this page:

"A basic understanding of [actions](https://docs.microsoft.com/en-us/composer/concept-dialog#action), [language genertion](https://docs.microsoft.com/en-us/composer/concept-language-generation), and [language understanding](https://docs.microsoft.com/en-us/composer/concept-language-understanding) in Composer."

"genertion" is missing an 'a'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b45a275f-7b99-3611-589c-76774e23b35f
* Version Independent ID: 5c85f403-d998-ff31-a08e-6bb9d3a8cdb9
* Content: [Create custom actions in Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions)
* Content Source: [composer-docs/how-to-create-custom-actions.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-create-custom-actions.md)
* Service: **bot-composer**
* GitHub Login: @emgrol
* Microsoft Alias: **v-eolshefski**

**Comment by emgrol** [comment]
Thanks for pointing this out, the fix is live.
