### ISSUE TITLE
Link to  Core Assistant template gets 404

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/composer-docs#197]
The bad link is right under the heading "Core Assistant Bot template".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae86dcdb-fc63-630a-e45f-a90a41a9e328
* Version Independent ID: 60722ca6-74a1-8a73-4246-ffb352bb4814
* Content: [Templates available in Bot Framework Composer](https://docs.microsoft.com/en-us/composer/concept-templates#core-assistant-bot-template)
* Content Source: [composer-docs/concept-templates.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/concept-templates.md)
* Service: **bot-composer**
* GitHub Login: @emgrol
* Microsoft Alias: **v-eolshefski**

**Comment by emgrol** [comment]
Thanks Bruce, a link fix should go live shortly.

**Comment by emgrol** [comment]
Thanks for letting us know, the fix should go live shortly.
