### ISSUE TITLE
Next steps link is broken (404)

### ISSUE THREAD

**Issue by managedcoder** [MicrosoftDocs/composer-docs#2]
[Enter feedback here]
The "Next steps" section has a broken link when I click "Extend Composer with plugins."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd89c358-c073-9d98-3465-42bc8bc3da91
* Version Independent ID: 486b07ca-44a3-508e-7a00-28c773bc996b
* Content: [Host Composer as a Web App - Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-host-composer)
* Content Source: [composer-docs/how-to-host-composer.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-host-composer.md)
* Service: **bot-composer**
* GitHub Login: @benbrown
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @managedcoder thanks for reporting the broken link. 
For some reason the publishing team merged and release the content earlier. 
The "[Extend Composer with plugins](https://github.com/MicrosoftDocs/composer-docs-pr/pull/186)" article is in PR now and will go live soon.

**Comment by zxyanliu** [comment]
Hi @managedcoder FYI. The updated docs were published yesterday and the broken link was fixed.
This is the article you are looking for: https://docs.microsoft.com/en-us/composer/how-to-use-plugin

Thanks.

**Comment by zxyanliu** [comment]
Could you please close this issue since it is been addressed?
Thank you!!!
