### ISSUE TITLE
missing image(?) from Control conversation flow with actions in Composer

### ISSUE THREAD

**Issue by northernb39** [MicrosoftDocs/composer-docs#201]
[https://docs.microsoft.com/en-us/composer/how-to-control-conversation-flow?tabs=v2x#branch-switch-multiple-options](https://docs.microsoft.com/en-us/composer/how-to-control-conversation-flow?tabs=v2x#branch-switch-multiple-options) has the following text "See below how the Nick and Tom branches are added both in the property panel on the right and in the authoring canvas." but there is nothing below 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d87030e-8ead-9ee9-7c5b-18a000422fc0
* Version Independent ID: 9a3a4afc-a94d-278b-e125-6a4a309de9d1
* Content: [How to control conversation flow in Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-control-conversation-flow?tabs=v2x)
* Content Source: [composer-docs/how-to-control-conversation-flow.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-control-conversation-flow.md)
* Service: **bot-composer**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-eolshefski**

**Comment by JonathanFingold** [comment]
Fix is live.
