### ISSUE TITLE
Hero Card Customization

### ISSUE THREAD

**Issue by JoseKPG** [MicrosoftDocs/composer-docs#205]
Hero Card Customization is not included in the docs. I have successfully customized hero card using webchat and will post the tutorial here for review to be included in the corresponding doc for future use.

1. Implement bot using web chat BOT ID method.
2. Run bot using webchat and use inspect element to verify class name of item wanting to customize. (In this example I will customize the button list of a hero card)
![image](https://user-images.githubusercontent.com/110568157/183914362-1282ef6f-b9be-45e1-a6c5-7b0f971633f4.png)
3. Verify name of class which in this case is: button.ac-pushButton.style-default.ac-selectable
4. Using a code editor, customize class to obtain desired look. (The following code is the one I used to obtain my desired result and will use as an example)
![image](https://user-images.githubusercontent.com/110568157/183914478-4e9e4c57-5b55-4af0-b733-d51b2ff4eca8.png)
5. After using code editor to customize my desired element, the result was the following:
![image](https://user-images.githubusercontent.com/110568157/183914545-937dbbf5-ec87-4f8f-b435-448ea2cbc1ee.png)

As far is I have tested, using this method is not limited to hero cards as it has worked on every element I have tried to customize.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83aee89-68c9-a192-b40b-a718efd00cf7
* Version Independent ID: 2eda2def-113e-ac41-0c2f-c8c0405ec2a1
* Content: [Respond with cards using Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-send-cards?tabs=v2x#herocard)
* Content Source: [composer-docs/how-to-send-cards.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-send-cards.md)
* Service: **bot-composer**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-eolshefski**

**Comment by JonathanFingold** [comment]
Fix is live.
