### ISSUE TITLE
Slight change to page

### ISSUE THREAD

**Issue by nickfrancis** [MicrosoftDocs/composer-docs#206]
For clarity would suggest changing step 12 on page 2. Currently the code seems to suggest using "Outlook" in the JSON - but it should be whatever name you assigned in Step 4.

The instruction also says to use the value from Step 3 - should be Step 4.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52929f3d-e53a-627a-9f18-cf4abc57dd6c
* Version Independent ID: 720e888d-7e2d-cb37-f445-7072cdf4f984
* Content: [Tutorial: Build an Enterprise People Bot with Bot Framework Composer](https://docs.microsoft.com/en-us/composer/templates/enterprise-people-tutorial)
* Content Source: [composer-docs/templates/enterprise-people-tutorial.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/templates/enterprise-people-tutorial.md)
* Service: **bot-composer**
* GitHub Login: @emgrol
* Microsoft Alias: **v-eolshefski**

**Comment by JonathanFingold** [comment]
Changes are in and should be live later today.
