### ISSUE TITLE
Enterprise People Bot list not working in Teams

### ISSUE THREAD

**Issue by nickfrancis** [MicrosoftDocs/composer-docs#210]
I'm aware there is a similar issue but mine appears to be slightly different....

When using my Bot in Teams, if there are multiple matches it throws an error:
![image](https://user-images.githubusercontent.com/115018551/199733689-f83a9b48-d1a1-494d-9d1f-69cb0ff16941.png)

Same feature works absolutely fine in Emulator / WebChat
![image](https://user-images.githubusercontent.com/115018551/199733995-af5c93aa-0693-4804-9935-d5b373ebb951.png)

If I look in Azure all I see is this:
![image](https://user-images.githubusercontent.com/115018551/199734128-459ecf13-001b-479e-8895-7fb550a084a3.png)

I've tried to hunt through Azure analytics to see if I can narrow down the error but can't find anything.

I've checked the cards file & can see it's using Adaptive Cards, not List Cards so it's not that.

Any input welcome :)

**Comment by dmvtech** [comment]
Hi @nickfrancis 

Can you please open this bug in the following repository:
https://github.com/microsoft/botframework-components

**Comment by nickfrancis** [comment]
Have done. Will close this issue.
