### ISSUE TITLE
Connect to [Telephony] link is broken

### ISSUE THREAD

**Issue by vmuthusamy-nlg** [MicrosoftDocs/composer-docs#211]
The below link is broken. 

Connect to [Telephony](https://github.com/microsoft/botframework-telephony#documentation-and-samples)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 713d1b02-5a3e-1bb4-d4e7-b33d94861a08
* Version Independent ID: 14445098-165a-6585-3c66-001f4b142c6d
* Content: [Authoring speech experiences in Bot Framework Composer](https://learn.microsoft.com/en-us/composer/concept-speech?tabs=v2x)
* Content Source: [composer-docs/concept-speech.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/concept-speech.md)
* Service: **bot-composer**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@vmuthusamy-nlg -- I tested the link this morning, `https://github.com/microsoft/botframework-telephony#documentation-and-samples`. It appears to resolve correctly. Perhaps it was a transient error.

**Comment by JonathanFingold** [comment]
@vmuthusamy-nlg -- The telephony channel is not accepting new customers. I'll update the article.

**Comment by vmuthusamy-nlg** [comment]
@JonathanFingold sure, thank you! Any tentative date about when it will be back again?

**Comment by JonathanFingold** [comment]
Unfortunately, I haven't heard of any plans to open it up again yet.
