### ISSUE TITLE
# is not a valid comment for trigger phrases

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/composer-docs#23]
The docs show this snippet:

``` lu
# help
- help
- I need help
- please help me
- can you help
```

However, this will be translated changed to:

``` lu
- \#help
- help
- I need help
- please help me
- can you help
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c55e6920-2987-2b78-66b7-3dee92ab8689
* Version Independent ID: 5d9f5e75-ee25-cc5d-bdd5-594712badf63
* Content: [Tutorial: Add language understanding to bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis)
* Content Source: [composer-docs/tutorial/tutorial-luis.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-luis.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi, Thanks for reporting the issue. 
`#` is not a comment for trigger phrases, it is the intent. 
`>` is how to comment in lu.
Please read the .lu file format [here](https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lu-file-format?view=azure-bot-service-4.0#add-comments).

**Comment by paulomorgado** [comment]
OK!

Shouldn't this:

```
 - cancel
 - please cancel
 - stop that
```

be:

```
# cancel
- cancel
- please cancel
- stop that
```

then?

**Comment by zxyanliu** [comment]
You can decide how to define the intent with the trigger phrases.
In the [doc](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis) you pointed to, you do not need to repeat the intent in the Trigger phrase field. It should be something like this: 

![Uploading image.png…]()

**Comment by paulomorgado** [comment]
I don't think that's what the [doc](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis) says.

At https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis#add-language-understanding-data-and-conditions points 1 to 3, it indicates to add a trigger using the Design surface and enter that configuration on the **Trigger phrases** text box.

Points 5 and 6 say to repeat points 1 to 3. It doesn't say to go to the user input and that configuration is invalid for the way it is telling the user to do.

Am I missing something?

**Comment by zxyanliu** [comment]
Well, you do not need to view the .lu files unless you want you.
But you touched a good point I think we should update in the docs. 
Apologies for the confusion. Will update this soon.

**Comment by zxyanliu** [comment]
Closing this issue since it is addressed. 
The updated content will go live soon.
Thanks again for your feedback.
