### ISSUE TITLE
Wouldn't NodeJS be a pre-req?

### ISSUE THREAD

**Issue by samaea** [MicrosoftDocs/composer-docs#3]
Wouldn't Node.JS be a pre-req too seeing as npm and node commands are being used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi!

Thanks for your report. Yes, Node.js is required and it is listed as an [installation prerequisite](https://docs.microsoft.com/en-us/composer/setup-yarn#build-composer-from-source). 

By the time users publish their bots, they should have [a basic bot built using Composer](https://docs.microsoft.com/en-us/composer/quickstart-create-bot), which is listed as a prerequisite in the [publish a bot](https://docs.microsoft.com/en-us/composer/how-to-publish-bot) article.

**Comment by samaea** [comment]
Isn't that a pre-requitise for those who have built Composer from source? If so, what about those who have installed Composer as a desktop executable?

**Comment by zxyanliu** [comment]
@samaea That's actually a good point! I will add it. 
Thanks a lot!!!

**Comment by zxyanliu** [comment]
FYI. I added Node.js as a prerequisite in the [publish](https://docs.microsoft.com/en-us/composer/how-to-publish-bot) article. 
The content is live now. 
Thanks again!

**Comment by samaea** [comment]
Awesome work, thank you!

**Comment by zxyanliu** [comment]
Thanks again for your feedback!!!
