### ISSUE TITLE
How to put validation on clientside?

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/composer-docs#33]
I tried isRequired, min, max for input fields but when these validations fail, the card is being re-thrown back at me on to client with empty fields, this looks like a serverside validation failing, i want this to be clientside validation please, how to implement that, tested in bot framework emulator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83aee89-68c9-a192-b40b-a718efd00cf7
* Version Independent ID: 2eda2def-113e-ac41-0c2f-c8c0405ec2a1
* Content: [Respond to users with cards - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-send-cards)
* Content Source: [composer-docs/how-to-send-cards.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-send-cards.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
I do not think Composer offers this feature for now. I am going to close this issue because it is not related to the docs.
For more issues and requests regarding the product itself, please report via https://stackoverflow.com/questions/62509541/bot-framework-composer
