### ISSUE TITLE
Missing condition

### ISSUE THREAD

**Issue by tiagonmas** [MicrosoftDocs/composer-docs#37]
In https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input 
In the "Create a number input action", in step 4 we add a if condition, but the condition is never set.
There is a missing step to set the Condition to user.result = 2.4 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce92ad12-27d2-3e3c-5a25-122cfc002837
* Version Independent ID: 52b6a9f0-2bf1-56e1-4044-54b89e69b81e
* Content: [Ask for user input - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input)
* Content Source: [composer-docs/how-to-ask-for-user-input.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-ask-for-user-input.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @tiagonmas thanks for your feedback.

You are right, the condition should not be empty. We will add the content. 

Also, FYI. The instructions are based on the [Asking Questions example](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input#the-asking-questions-example) where you will see the condition defined in the **Branch: If/else** action within the **Number input** action.

![image](https://user-images.githubusercontent.com/32497439/97612910-3dc54900-19d5-11eb-9feb-3fe105fa3125.png)

**Comment by zxyanliu** [comment]
The content was updated and merged. It will go live soon.
Thanks again for your feedback. Closing this issue now since it was resolved.
