### ISSUE TITLE
LUIS is no longer a recognizer choice

### ISSUE THREAD

**Issue by QuSibue** [MicrosoftDocs/composer-docs#4]
![image](https://user-images.githubusercontent.com/27338442/92252757-f89e0280-eece-11ea-8a81-9694f374b55c.png)

I downloaded the latest version of the composer in order to put my bot in French. Later, I wanted to add LUIS to my bot to do intention recognition with entities but I was disappointed to see that LUIS was no longer a choice in "Recognizer Type". In fact the menu has completely changed from "NONE, Regular Expression, LUIS" to "Default Recognizer, Regular Expression, Custom Recognizer".

So I would like to know how to make the tutorials (like https://docs.microsoft.com/en-us/composer/how-to-use-luis) of the documentation with the version 1.1.0 of the composer.

When I tried to select "Default recognizer" I get this error message
![image](https://user-images.githubusercontent.com/27338442/92254688-8d096480-eed1-11ea-8c0a-ecd6f4ddf8cf.png) 

NB : The error message doesn't appeared when English is set as bot's language

**Comment by zxyanliu** [comment]
Hi @QuSibue Thanks for reporting the issue.
The [updated docs](https://docs.microsoft.com/en-us/composer/) for Composer 1.1.1 release published yesterday. Please check the docs here: https://docs.microsoft.com/en-us/composer/

**Comment by QuSibue** [comment]
Hi @zxyanliu, thanks for the reply !

My issue is now resolved, I'll close it.

**Comment by zxyanliu** [comment]
Thanks!
