### ISSUE TITLE
Inconsitencies in features between Composer and SDK

### ISSUE THREAD

**Issue by anderl80** [MicrosoftDocs/composer-docs#44]
Maybe I get something wrong, but anyway, I guess we might need some clarification here.

In https://docs.microsoft.com/en-us/composer/introduction you state that the adaptive dialog is unique to Composer. But the SDK also offers adaptive dialogs https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-adaptive-dialog-introduction?view=azure-bot-service-4.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdf54a88-60d1-0f93-1b95-2a1adddaf51c
* Version Independent ID: 6045ccbf-e79c-61b8-59ac-61dec2bd3f82
* Content: [Introduction to Bot Framework Composer  - Bot Composer](https://docs.microsoft.com/en-us/composer/introduction)
* Content Source: [composer-docs/introduction.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/introduction.md)
* Service: **bot-composer**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Apologies for the confusion. Adaptive dialog is not unique to Composer.
Can you point out the content in the [introduction](https://docs.microsoft.com/en-us/composer/introduction) that made you think adaptive dialog is unique to Composer? We can fix it. Thanks.

**Comment by anderl80** [comment]
No problem, just checked the docs and wanted to reach out to you.

Please check the pragraph at https://docs.microsoft.com/en-us/composer/introduction#advantage-of-developing-bots-with-composer

> **Developers familiar with the Bot Framework SDK will notice differences between bots developed with it and Bot Framework Composer. Some of the advantages of developing bots in Composer include:
> - **Use of Adaptive Dialogs** allows for Language Generation (LG), which can simplify interruption handling and give bots character.
> - The visual design surface in Composer that eliminates the need for boilerplate code and makes bot development more accessible. You no longer need to navigate between experiences to maintain LU model as it is editable within the app.
> - Time saved with fewer steps to set up your environment.

**Comment by zxyanliu** [comment]
Hi, just let you know that we removed the content that you found confusing. 
Closing this issue because it is fixed and the content is live. 
Thanks!
