### ISSUE TITLE
Broken link: Further reading Adaptive dialog: Recognizers, rules, steps and inputs

### ISSUE THREAD

**Issue by scheyal** [MicrosoftDocs/composer-docs#47]
# Broken link (404)
## Further reading
Adaptive dialog: Recognizers, rules, steps and inputs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c5ffc7-459b-9220-9aa8-9e8fca5eab4b
* Version Independent ID: 4e819453-c172-82cb-8719-38b46c9ff9b4
* Content: [Triggers in Bot Framework Composer  - Bot Composer](https://docs.microsoft.com/en-us/composer/concept-events-and-triggers?source=docs)
* Content Source: [composer-docs/concept-events-and-triggers.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/concept-events-and-triggers.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Oops, let me fix it.

**Comment by zxyanliu** [comment]
## Further reading

- [Events and triggers in adaptive dialogs](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-adaptive-dialog-triggers)

**Comment by zxyanliu** [comment]
Hey @scheyal 
Thanks for reporting the issue. The PR to fix this issue was merged, and the content will go live soon.
Closing this issue for now. 

Thanks again for your feedback.
