### ISSUE TITLE
update screen shots

### ISSUE THREAD

**Issue by sadranyi** [MicrosoftDocs/composer-docs#5]
[Enter feedback here]
The screenshot for picking a recognizer has been updated in the latest version of the Bot Framework composer. 
It no longer includes the **none** option. Kindly update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ab5c58-4534-e181-008f-f5863d2df172
* Version Independent ID: 65b596ac-eecf-aaeb-9c86-af6ccbce3fc6
* Content: [Add dialog to your bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-add-dialog?source=docs)
* Content Source: [composer-docs/tutorial/tutorial-add-dialog.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-add-dialog.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @sadranyi thanks for reporting. 
The updated docs are on the way, will be published soon.

**Comment by zxyanliu** [comment]
@sadranyi FYI. The docs for Composer 1.1.1 was published yesterday. The screenshots were updated and published as well. 
Thanks again for your report. 

https://docs.microsoft.com/en-us/composer/

**Comment by sadranyi** [comment]
Awesome.
Cheers

**Comment by zxyanliu** [comment]
Thanks. You can feel free to close this issue since it's been addressed.

**Comment by sadranyi** [comment]
Sure

**Comment by zxyanliu** [comment]
Could you please close this issue since it's been addressed?
