### ISSUE TITLE
Camel case and Pascal case examples are interchanged

### ISSUE THREAD

**Issue by hinojosachapel** [MicrosoftDocs/composer-docs#50]
The article states in https://docs.microsoft.com/en-us/composer/concept-best-practices#name-dialogs-clearly:

**Some commonly used naming schemes include but are not limited to the following:**

- **Camel case: MyDialog**
- **Pascal case: myDialog**

The examples are swapped. Take a look at the Wikipedia: https://en.wikipedia.org/wiki/Camel_case

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed9348bd-7d44-a90b-019d-5f7496c1da1d
* Version Independent ID: 27a6a14d-f3ee-f0f4-6ee6-0648e42baba1
* Content: [Best practices in Bot Framework Composer - Bot Composer](https://docs.microsoft.com/en-us/composer/concept-best-practices)
* Content Source: [composer-docs/concept-best-practices.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/concept-best-practices.md)
* Service: **bot-composer**
* GitHub Login: @benbrown
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @hinojosachapel That's a nice catch!
Thanks for reporting the issue, fixing it now.

**Comment by zxyanliu** [comment]
Closing this because it is fixed.
