### ISSUE TITLE
Missing the $ syntax in discussion of "Memory in LG" section of doc

### ISSUE THREAD

**Issue by managedcoder** [MicrosoftDocs/composer-docs#53]
If you browse to https://docs.microsoft.com/en-us/composer/concept-memory#memory-in-lg you'll see what I think is a missing $ in the syntax of the discussion there were it mentions: 

"To use the value of a property from memory inside a message, wrap the property reference in curly brackets: {user.profile.name}"

I think it should read:

"To use the value of a property from memory inside a message, wrap the property reference in curly brackets and preface it with a '$' like this: ${user.profile.name}"

**Comment by zxyanliu** [comment]
Thanks for reporting the issue. We will fix it shortly.

**Comment by zxyanliu** [comment]
Thanks again for reporting the issue. We have updated the content and the doc will go live soon.
