### ISSUE TITLE
The Release Note URL is broken

### ISSUE THREAD

**Issue by anniexudan** [MicrosoftDocs/composer-docs#56]
Hi Team,

The Release Note for Bot composer 1.3 in the last section of this page is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a271c6e9-dd88-41b4-c45a-e6a58c91f9de
* Version Independent ID: 48d14b45-622d-5a3b-ed3e-5e427f747ee6
* Content: [What's new December - Bot Composer](https://docs.microsoft.com/en-us/composer/what-is-new)
* Content Source: [composer-docs/what-is-new.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/what-is-new.md)
* Service: **bot-composer**
* GitHub Login: @Kamrani
* Microsoft Alias: **v-liyan**

**Comment by zxyanliu** [comment]
Hi @anniexudan, that's a nice catch!
FYI. The release note should point to https://github.com/microsoft/BotFramework-Composer/blob/main/releases/1.3.0.md
Fixing it now. Thanks for your report.

**Comment by zxyanliu** [comment]
The fixing PR has been merged and the content will go live soon. Thanks again for your feedback! Closing this issue for now as it has been addressed.
