### ISSUE TITLE
The Switch Example is not Correct

### ISSUE THREAD

**Issue by cxbuilders** [MicrosoftDocs/composer-docs#58]
Should be:
# TestTemplate
- SWITCH: ${condition}
- CASE: ${case-expression-1}
    - output1
- CASE: ${case-expression-2}
    - output2
- DEFAULT:
   - final output

as can be found on: https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0

**Comment by zxyanliu** [comment]
@cxbuilders
That's a nice catch! Fixing now.
