### ISSUE TITLE
No option of hosting in a webapp?

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/composer-docs#6]
Seriously there got to be a way to host composer in webapp, is there such an option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd89c358-c073-9d98-3465-42bc8bc3da91
* Version Independent ID: 486b07ca-44a3-508e-7a00-28c773bc996b
* Content: [Host Composer as a Web App - Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-host-composer)
* Content Source: [composer-docs/how-to-host-composer.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-host-composer.md)
* Service: **bot-composer**
* GitHub Login: @benbrown
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Thanks for your question.
Do you have a specific feature request we can fulfill?

**Comment by zxyanliu** [comment]
Any updates?

**Comment by zxyanliu** [comment]
There is no such an option as you mentioned. 
Closing this issue for now. Thanks!
