### ISSUE TITLE
How to add the image to ThumbnailCard

### ISSUE THREAD

**Issue by tiagonmas** [MicrosoftDocs/composer-docs#68]
The doc would improve if there is some clarification on how to add the icon to the ThumbnailCard.

[ThumbnailCard
    title = Weather for ${dialog.weather.city}
    text = The weather is ${dialog.weather.weather} and ${dialog.weather.temp}&deg;
    image = ${dialog.weather.icon}
]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9be9f7b5-d020-0b8d-a282-67d60d4edf4b
* Version Independent ID: 19ae4e68-6c6b-8b84-a113-e3b7481e530d
* Content: [Tutorial: Add cards to a bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-cards)
* Content Source: [composer-docs/tutorial/tutorial-cards.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-cards.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @tiagonmas thanks for reporting this issue. We are investigating the issue you brought up.

**Comment by JonathanFingold** [comment]
@tiagonmas Did support get back to you on this? Are you still blocked?

**Comment by tiagonmas** [comment]
so long as passed that I do not even remember ... thanks anyway
