### ISSUE TITLE
404 on link Quickstart: Create a Cognitive Services resource using the Azure portal

### ISSUE THREAD

**Issue by tiagonmas** [MicrosoftDocs/composer-docs#69]
The link Quickstart: Create a Cognitive Services resource using the Azure portal  goes to 404 not found.
https://docs.microsoft.com/en-us/cognitive-services/cognitive-services-apis-create-account

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c55e6920-2987-2b78-66b7-3dee92ab8689
* Version Independent ID: 5d9f5e75-ee25-cc5d-bdd5-594712badf63
* Content: [Tutorial: Add language understanding to bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis)
* Content Source: [composer-docs/tutorial/tutorial-luis.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-luis.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @tiagonmas thanks for reporting the issue!
I am working on the fix now.
FYI. The link should point to: https://docs.microsoft.com/en-us/azure/cognitive-services/cognitive-services-apis-create-account

**Comment by zxyanliu** [comment]
Closing this issue as the fixing PR got merged. The content will go live soon. Thanks!
