### ISSUE TITLE
Luis Azure Resource information

### ISSUE THREAD

**Issue by tiagonmas** [MicrosoftDocs/composer-docs#70]
The information in step 7. is no longer updated with how LUIS presents things.
The screenshot should be updated. 

Also, the bot settings ask for a LUIS endpoitn key, and it's not clear where we get that key from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c55e6920-2987-2b78-66b7-3dee92ab8689
* Version Independent ID: 5d9f5e75-ee25-cc5d-bdd5-594712badf63
* Content: [Tutorial: Add language understanding to bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis)
* Content Source: [composer-docs/tutorial/tutorial-luis.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-luis.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @tiagonmas thanks for reporting the issue. We actually noticed this issue as well and are doing a patch release of the docs coming soon.
