### ISSUE TITLE
Adding a condition to validate LUIS score

### ISSUE THREAD

**Issue by tiagonmas** [MicrosoftDocs/composer-docs#71]
In Step 4 it's not clear if we need to use Cancel.Score or CancelScore.
The text says #Cancel.Score >= 0.8. but the image shows #CancelScore >= 0.8. (without ".").
Also, when we try to enter a value in the condition, we first need to select from true, false or "write an expression".
If we pick "write an expression", then the "=" is added. So, the value that is in the condition field is "=#Help.Score >= 0.5". Should the first "=" be there ? it's not clear from the instructions.
Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c55e6920-2987-2b78-66b7-3dee92ab8689
* Version Independent ID: 5d9f5e75-ee25-cc5d-bdd5-594712badf63
* Content: [Tutorial: Add language understanding to bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis)
* Content Source: [composer-docs/tutorial/tutorial-luis.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-luis.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @tiagonmas thanks for reporting the issue. We actually noticed this issue as well and are doing a patch release of the docs coming soon.

**Comment by tiagonmas** [comment]
and what is the right way :) ? can you share now ?

**Comment by zxyanliu** [comment]
Sure. FYI. The following should work:

![image](https://user-images.githubusercontent.com/32497439/103238877-e114da80-4900-11eb-983b-dc37c4a99b8c.png)

Btw, did you figure out how to find your LUIS authoring key yet?
