### ISSUE TITLE
Import existing Azure resources issue

### ISSUE THREAD

**Issue by tiagonmas** [MicrosoftDocs/composer-docs#74]
If I want to import existing resources (in my case because I'm getting an [error when creating the resources via composer](https://github.com/MicrosoftDocs/composer-docs/issues/73)), it's not clear what resources need to be created and where we get the information from in order to update the json.  The "Import existing Azure resources" section would benefit from more information on how to do this manually.

I'm looking at the [Bot Framework SDK documentation](https://docs.microsoft.com/en-us/composer/how-to-publish-bot) as a reference to see if I can do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @tiagonmas which SDK documentation are you reading as a reference? The one you shared still point to https://docs.microsoft.com/en-us/composer/how-to-publish-bot

**Comment by tiagonmas** [comment]
Sorry, sent the wrong link. I'm looking at https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp but also not having a lot of luck there as the ARM template is giving me some error :(

**Comment by zxyanliu** [comment]
Did you get any progress on this?

**Comment by tiagonmas** [comment]
not yet as I was hoping to get more guidance from you or resolution on the open issues.

**Comment by tiagonmas** [comment]
Any more guidance on how we can publish our bot manually ? Need a work around to the [publish bot functionality not working](https://github.com/MicrosoftDocs/composer-docs/issues/73). We have the solution runtime that I think has everything that is needed to publish the bot. It's just not clear what steps we manually need to do, things to configure ... would be great to have that documented.

**Comment by zxyanliu** [comment]
The content to Import existing Azure sources is being updated but not yet published.
It is recommended that you read instructions in the following issue: 

https://github.com/microsoft/BotFramework-Composer/issues/5456#issuecomment-777870194

**Comment by tiagonmas** [comment]
I've been using the workaround to e #73 and it's working fine. So I don't need to publish manually any more. thanks

**Comment by zxyanliu** [comment]
Cool! I am working on a script-based provision and publish article. Will keep you posted on this. Closing this issue for now. 
Thanks again for your patience.
