### ISSUE TITLE
Specify that the csproj file inside the runtime\azurewebapp folder 

### ISSUE THREAD

**Issue by tiagonmas** [MicrosoftDocs/composer-docs#77]
In Step 2 of [Customize the exported runtime](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#customize-the-exported-runtime) the example of link to the csproj file is incorrect. The csproj file is currently inside the runtime/azurewebapp folder. not at the root of runtime folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b45a275f-7b99-3611-589c-76774e23b35f
* Version Independent ID: 5c85f403-d998-ff31-a08e-6bb9d3a8cdb9
* Content: [Customize actions - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#export-runtime)
* Content Source: [composer-docs/how-to-add-custom-action.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-add-custom-action.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
@tiagonmas thanks for reporting the issue.
That's what the doc says in step 2 of the [customize the exported runtime](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#customize-the-exported-runtime) step: "Navigate to the `csproj` file inside the `runtime` folder". 

Will (`runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj`) be less confusing?

**Comment by tiagonmas** [comment]
right! It's a minor issue, I think it would be best to say "Navigate to the csproj file inside the runtime/**azurewebapp** folder". (dspite the fact that the example is right)

**Comment by zxyanliu** [comment]
Cool. Thanks, updating the wording to the following:

Navigate to the `csproj` file inside the `runtime\azurewebapp` folder (for example, `bot\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj`). 

Thanks for your feedback!
