### ISSUE TITLE
"Properties in the **user scope**" for #2 should actually be **conversation scope**

### ISSUE THREAD

**Issue by EricDahlvang** [MicrosoftDocs/composer-docs#8]
1.user is associated with a specific user. Properties in the user scope are retained forever.

2.conversation is associated with the conversation id. Properties in the **user scope** are retained forever and may be accessed by multiple users within the same conversation (for example, multiple users together in a Microsoft Teams channel).

#2 is talking about 'conversation scope' not 'user scope', and i think conversation scoped properties have a lifetime of the conversation itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9b361b0-d9e1-e57d-63ca-9056f54baf67
* Version Independent ID: b829d6b1-8859-27c9-0143-c064f0d03264
* Content: [Manage conversation flow in Bot Framework Composer  - Bot Composer](https://docs.microsoft.com/en-us/composer/concept-memory)
* Content Source: [composer-docs/concept-memory.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/concept-memory.md)
* Service: **bot-composer**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @EricDahlvang 
Thanks for reporting the issue. I agree with what you said. 
Updated in this PR: https://github.com/MicrosoftDocs/composer-docs-pr/pull/218

**Comment by alevinetx** [comment]
I see this page has been changed, per the initial comment.  But was it changed correctly?  I'm not sure, so I'm looking for verification before opening another issue.  I don't claim to fully understand the scopes, but this doesn't logically seem correct.

The original context above makes sense IRT ```conversation``` scope, and how properties may be accessed by multiple users (those in a channel).  

```conversation is associated with the conversation id. Properties in the conversation scope may be accessed by multiple users within the same conversation (for example, multiple users together in a Microsoft Teams channel).```

The change now shows that these properties are on the ```user``` scope and may be accessed by multiple users.

```
1. user is associated with a specific user. Properties in the user scope are retained forever and may be accessed by multiple users within the same conversation (for example, multiple users together in a Microsoft Teams channel).

2. conversation is associated with the conversation id. Properties in the conversation scope have a lifetime of the conversation itself.
```

**Comment by EricDahlvang** [comment]
@alevinetx the change is incorrect.  It should read as follows:

1. `user` is associated with a specific user. Properties in the user scope are retained forever and may be accessed by a single user.

1. `conversation` is associated with the conversation id. Properties in the conversation scope have a lifetime of the conversation itself. Properties in the conversation scope are retained forever and may be accessed by multiple users within the same conversation (for example, multiple users together in a Microsoft Teams channel).

**Comment by zxyanliu** [comment]
Apologies for the confusion. Updating the content to make it more clear.

**Comment by zxyanliu** [comment]
@EricDahlvang do you have some freecycle to review [this PR](https://github.com/MicrosoftDocs/composer-docs-pr/pull/285)?

**Comment by EricDahlvang** [comment]
thanks @zxyanliu !

**Comment by zxyanliu** [comment]
@alevinetx @EricDahlvang 
FYI. The PR to fix this issue was merged to master. Thanks for bringing this up!

**Comment by zxyanliu** [comment]
The [content](https://github.com/MicrosoftDocs/composer-docs-pr/blob/master/composer-docs/concept-memory.md) was in master and it will go live after our next master-live sync. Closing this issue for now.

Thanks again for your feedback. : -)
