### ISSUE TITLE
Rename CustomActionComponentRegistration to MultiplyDialogComponentRegistration

### ISSUE THREAD

**Issue by tiagonmas** [MicrosoftDocs/composer-docs#80]
The example works, but I think it would be more clear if CustomActionComponentRegistration  is renamed to MultiplyDialogComponentRegistration so it is clear that it is tied to Multiply, and that we need to register also any other new custom actions that we build afterwards.

 would rename that class, and also update the Startup.cs to reflect that
```
   // This is for custom action component registration.
   ComponentRegistration.Add(new MultiplyDialogComponentRegistration());

```
it was not very clear what needed to be updated when I added a second custom action. and I think this makes it clearer. Also, would be great to add a note on what needs to be done to add a second custom action.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b45a275f-7b99-3611-589c-76774e23b35f
* Version Independent ID: 5c85f403-d998-ff31-a08e-6bb9d3a8cdb9
* Content: [Customize actions - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#customize-the-exported-runtime)
* Content Source: [composer-docs/how-to-add-custom-action.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-add-custom-action.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Thanks for your feedback. I think `CustomActionComponentRegistration()` is intended to be general instead of specific in this case. If you have questions regarding the code, this might not be the repo you should file an issue. :-)

**Comment by tiagonmas** [comment]
This is a documentatio of the code issue :) I think would be better to name it after the custom action you are building as each new custom action that is created needs to be registered.

I created two custom actions, and had to register them both. So it makes sense that the registration is specific to the custom action. It is not generic. Unless I got it wrong.

Here is how I added two custom actions:
![Captura de ecrã 2021-01-06 175634](https://user-images.githubusercontent.com/42462/103803488-8b4ed980-5048-11eb-8bdc-d182e654ddfd.png)

And in Startup.cs
```
            // This is for custom action component registration.
            ComponentRegistration.Add(new MultiplyDialogComponentRegistration());
            ComponentRegistration.Add(new GamesOptionsDialogComponentRegistration());
```
so I do think this article would benefit from adding these suggestions.

**Comment by zxyanliu** [comment]
@tiagonmas cool! I am going to discuss with our dev for suggestions on this. 
Thanks again for your feedback! :-)

**Comment by tiagonmas** [comment]
FYI, I am a FTE ... just flagging since you tagged this as source:customer.

**Comment by zxyanliu** [comment]
Got it! Let me fix it now! Thanks!

**Comment by zxyanliu** [comment]
I talked to our developer about this specific issue you brought up. She said we are not changing this class name at this point. cc: @luhan2017

Thanks again for your feedback.

**Comment by tiagonmas** [comment]
Because it does not make sense or because lack of time ? I struggled with it, and I think this would help others!

**Comment by zxyanliu** [comment]
Adding @luhan2017 Can you help take a look?
