### ISSUE TITLE
Unable to link bot built from bot composer with twilio

### ISSUE THREAD

**Issue by Akshayvh94** [MicrosoftDocs/composer-docs#84]
I'm facing some some problem with linking bot with twilio. We have published bot in azure function and also as web app, having url https:// xyzbot.azurewebsites.net/api/messages
When we hit this end point we are getting 400 error.

Raised a same query in [stakcoverflow](https://stackoverflow.com/questions/65629466/unable-to-link-the-bot-built-from-bot-composer-with-twilio?r=SearchResults)

Please add your inputs or if there are other way to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
I am currently coordinating with our developers regarding this issue. Will get back to you as soon as I get responses from them. Thanks.

**Comment by zxyanliu** [comment]
Also I found some content from the SDK documentation for your reference:
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-twilio?view=azure-bot-service-4.0

**Comment by mmiele** [comment]
@Akshayvh94 Our apologies for the delay. Were you able to solve the issue you described? If not try, to use the following package:
![image](https://user-images.githubusercontent.com/2974753/128082734-b02778a6-1f4a-485a-920b-179e8a805ff2.png)
Hope this helps

**Comment by JonathanFingold** [comment]
Fix is in PR.

**Comment by mmiele** [comment]
Added clarifying note.
