### ISSUE TITLE
Outdated documentation about plugins

### ISSUE THREAD

**Issue by alexmoraru25** [MicrosoftDocs/composer-docs#85]
The documentation about plugins seem to be broken. All the links to the plugins directory are broken and there are no more samples of how to build a plugin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 360e9f8e-4f51-0feb-f286-af18fc111573
* Version Independent ID: c78e1f23-864c-7c68-aeab-30565ac5f980
* Content: [Extend Composer with plugins - Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-use-plugin)
* Content Source: [composer-docs/how-to-use-plugin.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-use-plugin.md)
* Service: **bot-composer**
* GitHub Login: @benbrown
* Microsoft Alias: **v-liyan**

**Comment by zxyanliu** [comment]
@alexmoraru25 thanks for reporting. 
I will address the issue soon. Thanks!

**Comment by zxyanliu** [comment]
The fixing PR was merged yesterday and the content will go live soon. Thank!
