### ISSUE TITLE
Add content about how to work with dynamic multiple choice and arrays

### ISSUE THREAD

**Issue by zxyanliu** [MicrosoftDocs/composer-docs#89]
Parent:

https://github.com/microsoft/BotFramework-Composer/issues/2232

**Comment by philip-mc** [comment]
I go round in a loop if I follow your comment/link

**Comment by zxyanliu** [comment]
@philip-mc I reproduced your code and got the exact issue you had. My guess is that when we initialize an array that contains multiple objects, we might need specific settings in the multi-choice prompt to make it work. 

While still investigating your problem, I'd like to share some basic steps to use a dynamic multi-choice prompt in Composer. P.S. We used to have a "dynamic" setting which was removed from Composer for some reason. These instructions are based on what I experimented with from my end and the comments shared by @hibrenda on [this original issue](https://github.com/microsoft/BotFramework-Composer/issues/2232).

1. Let's set a property and assign an array of strings as its property value.
2. Then we create a multi-choice prompt. 
   - Enter the text you would like to prompt in the **Bot Asks** seciton.
   - In the **User Input** section, set **List style** to `auto` and set the value of Array of choices to `=thePropertyNameSetInStep1`

The following are the code for your reference: 

![image](https://user-images.githubusercontent.com/32497439/105926861-ad100080-5ff7-11eb-9bd8-f1c44cfb2faf.png)

Testing in Emulator:

![image](https://user-images.githubusercontent.com/32497439/105926954-d2047380-5ff7-11eb-8114-8ba8852e4d6b.png)

**Comment by philip-mc** [comment]
Thank you so much for the assistance. It was the strucutre of the array that had it spluttering:

![image](https://user-images.githubusercontent.com/73343537/105985899-104f7080-6094-11eb-90c3-8cebf07a8818.png)

The expression was replaced with the lower one and it worked straight away. For the documentation can I recommend examples are added all the way along as these are the most valuable tool I have in getting dialogs working :D

**Comment by zxyanliu** [comment]
This is good feedback. Thanks a lot! I will add some content to this article soon.
Thanks again.
