### ISSUE TITLE
Implementing Middleware with Bot Composer

### ISSUE THREAD

**Issue by zxyanliu** [MicrosoftDocs/composer-docs#9]
Transferring from https://github.com/MicrosoftDocs/bot-docs/issues/1874
We don't have a plan to work on this topic soon, but will backlog for future work.

**Comment by Silu321** [comment]
how to connect what's app on my own AZURE-Bot.

**Comment by zxyanliu** [comment]
> how to connect what's app on my own AZURE-Bot.

Hi @Silu321 I don't think this question is related to Composer docs. 
Can you ask your question in [StackOverFlow](https://stackoverflow.com/questions/tagged/botframework)?

**Comment by zxyanliu** [comment]
FYI. The botframework-sdk readme has the [official list](https://github.com/microsoft/botframework-sdk#channels-and-adapters) of channels and channel adapters (for the SDK, Botkit, and community repos). Looks like there's a WhatsApp channel adapter in a [community](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet#adapters) repo. 
Please take a look there.
