### ISSUE TITLE
Process does not allow to select correct subscription

### ISSUE THREAD

**Issue by lafe** [MicrosoftDocs/composer-docs#91]
The dialog to create new resources does not allow to change the Azure tenant. Therefore, users that belong to multiple tenants can only select subscriptions which are in their default tenant - other tenants (test and customer tenants) are unreachable. The issue has been raised in the [BotFramework-Composer](https://github.com/microsoft/BotFramework-Composer/issues/5459) repository, but was closed without a clear resolution. The [best answer](https://github.com/microsoft/BotFramework-Composer/issues/5459#issuecomment-756320614) in that issue also states that there is currently no documentation for this scenario, which I believe to be common for Consultants.

EDIT: #86 is a similar issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
@lafe It seems that this is supported in Composer for now but will do for R13. Thanks again for opening this issue. I am closing this for now since it is not supported in the product now.
