### ISSUE TITLE
How do you log out?

### ISSUE THREAD

**Issue by BobGerman** [MicrosoftDocs/composer-docs#96]
The OAuth process worked great for me - first try!!
However I can't figure out a way to log off. I'm looking for the equivalent of

```javascript
botAdapter.signOutUser(context, connectionName);
```
Does this require writing a custom action? Thanks!

**Comment by BobGerman** [comment]
Never mind - figured it out

**Comment by zxyanliu** [comment]
@BobGerman sorry about my late response.
Can you share how to do it?
