### ISSUE TITLE
String is incompleted

### ISSUE THREAD

**Issue by josebispo** [MicrosoftDocs/composer-docs#97]
[Enter feedback here]

The sentence "Connect to a skill" now is "Connect to a remote skill", can help to beginners starting from scratch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a631930-1f27-93a4-7d70-79cdc6ee3bb3
* Version Independent ID: 8506ad08-a04a-31d6-46a0-24c4654c8705
* Content: [Connect to skills - Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill)
* Content Source: [composer-docs/how-to-connect-to-a-skill.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-connect-to-a-skill.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
@josebispo Thank you for your feedback. If I understood you correctly, there is a section in [this article](https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill#connect-to-the-skill-from-your-bot) titled **Connect to the skill from your bot**, I changed that to be more clear: **Connect to the remote skill**. 

In step #2 of that section it says:

> Add the **Access external resources > Connect to a skill** action to the trigger.

This is taken directly from the Composer action menu, so it needs to be a direct quote. If you feel that this should be changed, please feel free to create an issue in the [BotFramework-composer](https://github.com/microsoft/BotFramework-composer) repo and make that suggestion.

Please let me know if this did not address your concern.

**Comment by WashingtonKayaker** [comment]
Closing - no response. @josebispo if there is more to your feedback than I have addressed or if you have identified another issue in the documentation, please feel free to open a new issue.
