### ISSUE TITLE
Expand ChoiceInput documentation

### ISSUE THREAD

**Issue by garypretty** [MicrosoftDocs/composer-docs#98]
Our documentation for ChoiceInput today provides some basic instructions for using 'Simple Choices' but has no mention of the ability to add 'Structured Choices' to set synonyms etc. Additionally we do not cover / mention the Choice Options (e.g. inline separator etc.).  We hope that by adding this detail we can make the use of ChoiceInput clearer.

Additionally, for context, we have rasied an issue to have the Array of Choices property moved to the top of the User Input tab to make it more discoverable. Tracked here https://github.com/microsoft/botframework-components/issues/561

@zxyanliu this is the issue we discussed that you said you could pick up as a priority? It would be great to have this change made ahead of 1.4 if possible. Thanks.

**Comment by zxyanliu** [comment]
@garypretty Thanks for bringing this up. This doc is on my radar and changes will be made ahead of 1.4. Will let you know as soon as I have some update.

**Comment by zxyanliu** [comment]
This issue is also related: https://github.com/MicrosoftDocs/composer-docs/issues/89

**Comment by zxyanliu** [comment]
@garypretty Thanks again for filing this issue. Based on my investigation, I have some updates to share:

* **Structured Choices**
![image](https://user-images.githubusercontent.com/32497439/107997078-cb35a480-6f96-11eb-8fff-eb7c2bf12e29.png)
|Property | Description | Example |
    |------|------|------|
    |Choice name | The name of the choice and the value to return when this choice is selected.|`Test01`|
    | Synonym (Optional) | A list of synonyms to recognize in addition to the Choice name value. | `test1, test01`|
    | Action | Card action you define for this choice. | Needs investigation |
    
**Issues/Open questions regarding structured choices**: 
    1. We need more clarity regarding what are **simple choices** and **structured choices**. My current understanding is that **structured choices** supports a more advanced and customized definition of multiple choices, for example, you can define synonyms of a multiple choice. 
    2. It seems the **Action** property is optional. 
    3. I did not find any documentation regarding the card action definition in JSON. I need more investigation on this.
    4. It seems that there is a bug when **Add**ing a structured choice. The choice will disappear after I add it, however, sometimes, this works perfectly. Very wired.
    ![multi-choice-prompt](https://user-images.githubusercontent.com/32497439/107997696-3a5fc880-6f98-11eb-9792-557418a53851.gif)

* Choice options
This part of the content is already covered in the [additional-information-the-user-input-tab](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input#additional-information-the-user-input-tab) of the [Ask for user input](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input) article. You will need to scroll down the end of table to see the descriptions of such properties as `inline separator`, `Inline or`, and `Inline or more`. Besides the content covered, please let me know if there is anything else you want me to add about **Choice options**.

There is a Work In Progress PR for your reference here: https://github.com/MicrosoftDocs/composer-docs-pr/pull/376

**Comment by zxyanliu** [comment]
@hibrenda Please take a look to see if anyone knows how to use the "Structured choices." Thanks.

**Comment by zxyanliu** [comment]
@garypretty FYI. The multi-choice article has been updated in [PR376](https://github.com/MicrosoftDocs/composer-docs-pr/pull/376). Due to a lack of documentation on card definition using JSON format in Bot Framework, @tdurnford suggested I reference [this doc](https://docs.microsoft.com/en-us/javascript/api/botframework-schema/cardaction?view=botbuilder-ts-latest).

There are some similar card definitions in [the Teams doc](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions), but they are Teams specific.

**Comment by zxyanliu** [comment]
The content has been merged and will go live soon.
Closing this issue.
