### ISSUE TITLE
malformed link in language generation concept

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/composer-docs#99]
This bit of text is not rendering correctly:

```
Use the [import](common.lg) to import the common templates to a specific dialog.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8fd4a76-f071-477d-57b4-fd746c1c682e
* Version Independent ID: 3947e8f1-28bc-d8e3-daeb-b8522317700b
* Content: [Language generation in Bot Framework Composer - Bot Composer](https://docs.microsoft.com/en-us/composer/concept-language-generation)
* Content Source: [composer-docs/concept-language-generation.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/concept-language-generation.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hey @JonathanFingold The `[import](common.lg)` is the syntax to import the common templates to a specific dialog. Which part of the text did you think is not rendering correctly? Can you please be more specific? Thanks!

**Comment by JonathanFingold** [comment]
@zxyanliu , @WashingtonKayaker , Looks good with the edit.
